### ISSUE TITLE
Remove server dependencies

### ISSUE THREAD

**Issue by absolux** [Yoctol/bottender#10]
Good job guys for this library :+1: 

IMO you should drop the server dependencies (express, koa, restify ,micro, ngrok...) and only expose functions to initialize a new or existing apps. so instead of
```js
const { MessengerBot } = require('bottender');
const { createServer } = require('bottender/express');

const bot = new MessengerBot({
  accessToken: '__FILL_YOUR_TOKEN_HERE__',
  appSecret: '__FILL_YOUR_SECRET_HERE__',
});

bot.onEvent(async context => {
  await context.sendText('Hello World');
});

const server = createServer(bot);

server.listen(5000, () => {
  console.log('server is running on 5000 port...');
});
```
we can use this library within an existing express app
```js
let bottender = require('bottender')
let express = require('express')
let app = express()

let bot = new MessengerBot({
  accessToken: '__FILL_YOUR_TOKEN_HERE__',
  appSecret: '__FILL_YOUR_SECRET_HERE__'
})

bot.onEvent(async (context) => {
  await context.sendText('Hello World')
})

bot.initExpress(app)

// configure the app

app.listen(5000, () => {
  console.log('server is running on 5000 port...')
})
```

**Comment by chentsulin** [comment]
Hi @absolux, good to hear from you.

We ever think of some thing like `initExpress` before, but it violates the open/closed principle. We should not keep adding new methods to the bot:

```js
bot.initExpress(app)
bot.initKoa(app)
bot.initMirco(app)
bot.initRestify(app)

// future?
bot.initFastify(app)
bot.initHapi(app)
```

However, we have a plan to separate server framework modules into individual libraries, for example, `bottender-express`, `bottender-koa`. And other frameworks also could be supported by this way.

**Comment by absolux** [comment]
I agree with you @chentsulin it's fast as a solution but not good for maintainability

**Comment by chentsulin** [comment]
It has been done in the 1.0.0-alpha releases, so I'm going to close this issue.
