### ISSUE TITLE
How to set a conversation flow?

### ISSUE THREAD

**Issue by lucasansei** [Yoctol/bottender#109]
Can someone give me an example on how to build a multi-step conversation flow?

**Comment by chentsulin** [comment]
We have a lot of approaches using state to achieve step control. How about this one:

```js
bot.setInitialState({
  step: 1,
});
bot.onEvent(async context => {
  switch (context.state.step) {
    case 1:
      // ...do something in step 1
      context.setState({ step: context.state.step + 1 });
      break;
    case 2:
      // ...do something in step 2
      context.setState({ step: context.state.step + 1 });
      break;
    case 3:
      // ...do something in step 3
      break;
  }
});
```

**Comment by lucasansei** [comment]
Thanks! This worked perfectly!

**Comment by LintangWisesa** [comment]
Hi, Sir @chentsulin. I'm new to Bottender.js. I've successfully created a simple bottender on Express.js (+ngrok) with MongoDB database, but I have a little problem. How I can make a multi-step conversation flow in Bottender 1.4? I've tried use state, but still stucked. Thanks in advance

**Comment by chentsulin** [comment]
Hi @LintangWisesa, you can find [some latest examples](https://github.com/Yoctol/bottender-proposal-conversation/tree/master/examples) there using the [bottender-proposal-conversation](https://github.com/Yoctol/bottender-proposal-conversation) module to make multi-step conversations. You can try and see if it works in your use case.

**Comment by LintangWisesa** [comment]
Great, thanks Sir @chentsulin
