### ISSUE TITLE
[bug] ContextSimulator

### ISSUE THREAD

**Issue by roonie007** [Yoctol/bottender#116]
Hey guys,

```setState``` and ```resetState``` do not work in ```Handler``` when using ```ContextSimulator``` to simulate the Bot.

In my case to solve this problem , we have added an Overlay Module that override those functions, but I hope you can find a solution better than that 😄

**Comment by chentsulin** [comment]
Hi @roonie007, I open a PR #131 to simulate context internal state control.

It's worth mentioning that I am not sure state mutation should be applied immediately or should be applied to next event. Now it applies immediately, but I'm planning to have some experiments and see what's the pros and cons of them.

**Comment by roonie007** [comment]
Hey @chentsulin  , 

Thank you very much, I will try it on my side too and I will keep you updated 😉
