### ISSUE TITLE
CLI skip prompt for CI usage

### ISSUE THREAD

**Issue by kpman** [Yoctol/bottender#119]
Maybe `--skip-prompt` or `--no-prompt` ?

**Comment by wtflink** [comment]
我會直接 --yes

**Comment by kpman** [comment]
@chentsulin @xxhomey19 any idea?

**Comment by chentsulin** [comment]
`[-f|--force|-y|--yes]`

Just like `npm init` does: https://docs.npmjs.com/cli/init

**Comment by kpman** [comment]
`--force` is already taken by attachment force upload.
so `-y` & `--yes` is prefer and we should support both of them.
