### ISSUE TITLE
Custom bottender-lock.json path

### ISSUE THREAD

**Issue by kpman** [Yoctol/bottender#122]
https://github.com/Yoctol/bottender/blob/7c91298d338080c99d50cde0c56a33caf1f53ba0/src/cli/providers/messenger/attachment.js#L117

**Comment by xxhomey19** [comment]
I can tackle it, but what's the option name for the path of `bottender-lock.json` preferred?

**Comment by kpman** [comment]
I prefer `--lockfile`.
Do you guys have any idea? @chentsulin @tw0517tw @LittleWhiteYA

**Comment by tw0517tw** [comment]
`--lockfile` looks good,

**Comment by chentsulin** [comment]
We will introduce a brand new mechanism to handle this, so I am going to close this issue now.
