### ISSUE TITLE
[LINE] how to push message without context

### ISSUE THREAD

**Issue by wingliu0** [Yoctol/bottender#133]
the push function looks like this
```await context.client.pushText(userId, 'Goodbye LINE');```

but in most usecase, I would like to push message at a specific time, or triggered events other than LINE webhook events. 
How should I push messages whenever I like to?
ps: Im currently saved a context object to global scope. so that whenever I need to call ```.pushText```. I can use the global context object.

**Comment by tw0517tw** [comment]
You can directly use the underlying client package [`messaging-api-line`](https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-line).

**Comment by chentsulin** [comment]
Example:

```js
const { LineClient } = require('messaging-api-line');

const client = LineClient.connect(accessToken);

client.pushText(userId, 'Goodbye LINE');
```

**Comment by slidenerd** [comment]
Would this be akin to proactive messaging?

**Comment by chentsulin** [comment]
Sure, this usage is exactly proactive messaging.
