### ISSUE TITLE
How to send only once one message?

### ISSUE THREAD

**Issue by sgaseretto** [Yoctol/bottender#134]
When I run the examples for messenger, once I send something to the bot, it starts spamming the same thing until I stop the server, how do I send a message only once and wait for the user to respond?
Here is an example of what I'm talking:
![img_3630](https://user-images.githubusercontent.com/6946040/34413831-874cc928-ebc4-11e7-9bca-235b8156276d.jpg)

**Comment by wtflink** [comment]
Seems like your bot keep receiving the "message_echoes" event. 
Set your webhook properly or filter onEcho event to stop the bot from self responding.
You can also check the official webhook setting documents  for more info. 
ref: https://developers.facebook.com/docs/messenger-platform/webhook

**Comment by sgaseretto** [comment]
Thanks a lot, it was the "message_echoes" event

**Comment by chentsulin** [comment]
Or you can filter echo events explicitly in the handler:

```js
bot.onEvent(async context => {
  if (!context.event.isEcho) {
    await context.sendText('Hello World');
  }
});
```
