### ISSUE TITLE
Telegram bots in group chat should reply in group as default

### ISSUE THREAD

**Issue by Niko-La** [Yoctol/bottender#135]
how come data is showing up as object Promise.

console log is working fine

**Comment by chentsulin** [comment]
What is the return value of your `go` function?

If it returns a promise, you should wait for it:

```js
const result = await go();
await context.sendMessage(' PRICE: ' + result, options)
```

**Comment by Niko-La** [comment]
```
  .onText(/balance/i, async context => {
    console.log(context.session.user.id);

    const options = {
//      parse_mode: 'Markdown',
    };
    const result = await go();
});
    await context.sendMessage(' ZCOIN PRICE: ' + result , options);
  })
  .onEvent(async context => {
    await context.sendMessage("Sorry, I don't know what you say.");
```


```
`const axios = require("axios");
const url = "https://api.coinmarketcap.com/v1/ticker/zcoin/";

async function go() {
  try {
    // but first, coffee
    const wes = await axios(url);
    cmc = wes.data;
    console.log(cmc[0]); // mediocre code
//    return (JSON.stringify(data));
    return (cmc[0].rank);
  } catch (e) {
    console.error(e); // 💩
  }
}`
```


```
home/linuxnikola/EWbot/telegram-builder/index.js:61
    await context.sendMessage(' ZCOIN PRICE: ' + result , options);
          ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)

```


I have attached the original go function but also getting an error when placing the code as suggest.

**Comment by chentsulin** [comment]
When you get `SyntaxError: Unexpected identifier` with `await` keyword, it usually mean 
1. your node version < 7.6 (do not support async function)  
2. you put `await` keyword in a normal function, not async function

**Comment by Niko-La** [comment]
that did the trick.  able to reply.


FYI i tried deploying the bot in a group chat in telegram but all its replies are in private chat.

How do I make the bot to reply within the group chat?

when you receive a message it has both chat_id and from_id,
in group chat chat_id is different from from_id

await context.sendMessage(' ZCOIN PRICE: ' + result , options);


Any way to ensure that group chat get replies there?

**Comment by xxhomey19** [comment]
Hi @Niko-La 
As far as I know, Telegram bot are able to reply in group chat through [inline-mode](https://core.telegram.org/bots/api#inline-mode).

**Comment by Niko-La** [comment]
@xxhomey19 looking to just reply in the group chat. not use the inline option
Its important for the framework to work in group chats...

In the awat.content.sendMessage(''test', options)

is the options flag relevant to changing the variable to chat_id from from_id.

**Comment by chentsulin** [comment]
https://github.com/Yoctol/bottender/pull/148 should fix this bug

**Comment by chentsulin** [comment]
@Niko-La upgrade to https://github.com/Yoctol/bottender/releases/tag/v0.14.15 should fix it.
