### ISSUE TITLE
discord or telegram group chat for devs

### ISSUE THREAD

**Issue by Niko-La** [Yoctol/bottender#136]
can we aggregate the devs into a chat.  Seems ideal for a chatbot framework.

**Comment by chentsulin** [comment]
How about slack? We usually use slack to communicate dev tasks during our work and I also see it has a great success in [zeit community](https://zeit.co/chat).

**Comment by tw0517tw** [comment]
Discord servers are easier to join than Slack workspaces. With a simple link you can let others join a Discord server. But for auto joining Slack workspaces, you need to host a invitation service like [slackin](https://github.com/rauchg/slackin) and users need to accomplish a more complicate sign up process.

If we are going to setup a chat service, I'll vote for Discord other than Slack.

**Comment by Niko-La** [comment]
I vote for Discord over Slack.  I agree with @tw0517tw  much easier and gaining in popularity.

**Comment by kpman** [comment]
We've created a Discord server for Bottender.
Feel free to join with us: https://discord.gg/rDxetUb

**Comment by Niko-La** [comment]
great. that is fanatastic.
