### ISSUE TITLE
Add multi-Line bot example

### ISSUE THREAD

**Issue by wingliu0** [Yoctol/bottender#141]
inspired by `Add multi-page example #60`

Is it possible to support multi-Line bot too?

I'm new to github and dont know how to fork and npm install my forked repo

**Comment by chentsulin** [comment]
In Messenger case, we can install one app to multiple pages and separate requests using `page_id`.

But it doesn't make sense in LINE case, we can only use one app for one LINE@ account and even can't get any information from raw event to separate requests:

```js
{
  "events": [
    {
      "replyToken": "nHuyWiB7yP5Zw52FIkcQobQuGDXCTA",
      "type": "follow",
      "timestamp": 1462629479859,
      "source": {
        "type": "user",
        "userId": "U206d25c2ea6bd87c17655609a1c37cb8"
      }
    }
  ]
}
```

**Comment by tw0517tw** [comment]
If you still want to use same handler for multiple LINE bots, you can check the [`cross-platform` example](https://github.com/Yoctol/bottender/blob/master/examples/cross-platform/index.js) and just setup many LINE bots with different `path`s.

Closing this now. Feel free to reopen if you have more idea or question.
