### ISSUE TITLE
Add slack access token in runtime

### ISSUE THREAD

**Issue by IniZio** [Yoctol/bottender#146]
Since i want to make the slack bot installable with oauth2, is there a method that i can use to add the access token after the bot instance is created?

Currently the token is added at `SlackBot` is run, which means i need to provide it at the constructor. However with oauth the token is given after the constructor is run. So now i just enter an empty string first and then manually change the `_token` property in `SlackOAuthClient`.

**Comment by tw0517tw** [comment]
Hi @IniZio , 

Thanks for your advice, we can try to implement custom access token in SlackBot, but we need to do some research to the installable Slack app usage to figure how to do it well.

Just guessing, what if you `new SlackBot()` after receiving the token, will it be better?

**Comment by IniZio** [comment]
I do not think that is possible, since it needs the `bot` parameter in `createServer(bot)`?

**Comment by tw0517tw** [comment]
Hi @IniZio ,

After reading some Slack documents, I guess we should try to support `mapTeamToAccessToken` in `SlackBot` like we have `mapPageToAccessToken` in `MessengerBot` (ref: [messenger-multi-pages](https://github.com/Yoctol/bottender/blob/master/examples/messenger-multi-pages/index.js#L12-L25) example).

After that, you can implement the OAuth procedure to save a team's ID and access token in a database and let the `mapTeamToAccessToken` function to read your database for access tokens.

**Comment by tw0517tw** [comment]
Although we have not implemented `mapTeamToAccessToken` yet, you can try `bottender@0.14.15` first.

As `bottender@0.14.15` using new version of underlying client (`messaging-api-slack@0.6.10`), you can put `{ token: YOUR_CUSTOM_TOKEN }` as options in `context.postMessage()`, `context.sendText()` and `context.postEphemeral()`.

**Comment by IniZio** [comment]
Thanks a lot for the update!
