### ISSUE TITLE
customer chat plugin ref param

### ISSUE THREAD

**Issue by souflam** [Yoctol/bottender#147]
i can't catch the Postback ref param in customer chat plugin
```
<div class="fb-customerchat"
 page_id="<PAGE_ID>"
 ref="<OPTIONAL_WEBHOOK_PARAM>">
</div>
```
this is my code:
```
bot.onEvent(async context => {
  await console.log(context.event.postback);
  //await context.sendText('je suis un robot boucle infinie :p');
});
```
it give me always null.
any suggestion please.

**Comment by tw0517tw** [comment]
Hi @souflam ,

Have you checked that you have already subscribed to the `messaging_postbacks` or `messaging_referrals` events on Facebook Developer site? You need to subscribe to them to get those events pushed to your webhook.

![default](https://user-images.githubusercontent.com/1003146/34785601-99e66b4a-f66c-11e7-9df2-96a394d6753e.png)

Also, if you try to get `referral`s from [existing conversations](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin?locale=en_US#steps), it will be in `context.event.referral`. (the `4. Optional. Handle the messaging_referrals event for existing conversations` part)

**Comment by souflam** [comment]
thnks @tw0517tw for the reply
i had checked all the events

Selected events: messages, messaging_postbacks, messaging_optins, message_deliveries, message_reads, messaging_payments, messaging_pre_checkouts, messaging_checkout_updates, messaging_account_linking, messaging_referrals, message_echoes, standby, messaging_handovers, messaging_policy_enforcement, hours |  
-- | --
 but i still can't get the postback from the param ref :(

**Comment by chentsulin** [comment]
Hi @souflam, there are some tips help you and us to debug in this situation:

1. You can run Bottender bots with `DEBUG=bottender/bot/Bot` env variable to see original http request body received from Messenger.

2. You can print the raw event in your handler:

```js
bot.onEvent(async context => {
  console.log(context.event.rawEvent);
});
```

Pasting log result here will be helpful. And You should only print `context.event.postback` when receiving `postback` event, so it wouldn't print null postback when receiving `message_reads` or `message_deliveries ` events:

```js
bot.onEvent(async context => {
  if (context.event.isPostback) {
    console.log(context.event.postback);
  };
});
```

**Comment by tw0517tw** [comment]
Hi @souflam ,

That's exactly how Messenger Customer Chat Plugin refs works.
- A new conversation start with clicking `Get Started` button, **one** `messaging_postbacks` event with `referral` is sent.
- A existing conversation continued from clicking `Chat now` one the plugin, **one** `messaging_referrals` event (the one in your comment) is sent.

So, yes, you should only get them one time in a conversation.

**Comment by souflam** [comment]
hi @tw0517tw ,
this is what i understand me too, i can catch this ref params only one time , thnks for your clarification.

**Comment by crydemon** [comment]
what can i do if use php
