### ISSUE TITLE
How to get the admin id sender instead of page id in bottender

### ISSUE THREAD

**Issue by souflam** [Yoctol/bottender#151]
any one has a idea how i can get a **sender id** (admin or editor) of a page instead of **page id** with bottender.

**Comment by tw0517tw** [comment]
Hi @souflam ,

I'm afraid that's not possible on Messenger Platform at this moment. The `echo` webhook events from Messenger only gives the information of sender page id, with no information of which individual (person or app/bot) sends the event.

You can also try asking in this Facebook Group. https://www.facebook.com/groups/messengerplatform/

**Comment by chentsulin** [comment]
AFAIK, we don't have this kind of information in [message_echoes](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-echoes) payload.

**Comment by chentsulin** [comment]
Hi @souflam, as we know, we can't have this feature even using any workaround at this moment. This should be a feature request on messenger side, so I am going to close this issue. Feel free to reopen this if you have any idea.
