### ISSUE TITLE
[Messenger] - How to update mapPageToAccessToken

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#154]
Hi,

I have an application that users create their ChatBot. So i want that when they click "Install ChatBot on your Page" the mapPageToAccessToken should be updated for live working. Is there a way to do this, without rebooting the server? 

Thanks,

**Comment by chentsulin** [comment]
@pavei `mapPageToAccessToken` is just a normal JavaScript function so you can implement it whatever you want.

In this case, we can query storage or API in `mapPageToAccessToken` function to get the token:

```js
async function mapPageToAccessToken(page) {
   const token = await getAccessTokenFromDatabaseOrAPI(page);
   return token; 
}
```

And you should update the storage when they click "Install ChatBot on your Page".

**Comment by pavei** [comment]
Thanks!
