### ISSUE TITLE
How to get user email in Messenger

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#157]
Hi,

I want to get the User Email. Looking the facebook docs, i can get it, but on "context.session" it dont get. 
https://developers.facebook.com/docs/facebook-login/permissions#reference-email

Is there a way to do this?

**Comment by tw0517tw** [comment]
Hi @pavei ,

The permissions in Messenger Platform is different from Facebook Login, so we can only get profile fields [listed in this document](https://developers.facebook.com/docs/messenger-platform/identity/user-profile#fields).

**Comment by chentsulin** [comment]
Or you can build your account system and a login page with [Facebook Login enable email permission](https://developers.facebook.com/docs/facebook-login/permissions/), then redirect your messenger users via button to specified login url and store the mapping in your side.

**Comment by pavei** [comment]
ah ok! Thanks for answering! @tw0517tw @chentsulin
