### ISSUE TITLE
accessToken is not required for messenger set webhook

### ISSUE THREAD

**Issue by kpman** [Yoctol/bottender#158]
When only using CLI to set webhook, the users don't need to provide `accessToken`.
They just need to set `appId` and `appSecret` in config.

So maybe we should tell the users to provide an empty string as `accessToken`?

**Comment by tw0517tw** [comment]
Put empty string or other non-token string in can be a workaround, but not a final solution.

**Comment by chentsulin** [comment]
Resolved by #159
