### ISSUE TITLE
Conversation ID 

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#160]
Hi, 

I want to track events using bottender. But i did't find "conversation id". I know that i can concat: "context.event.rawEvent.sender.id + context.event.rawEvent.recipient.id, but i would like to know if is there a conversation id? 

Thanks,

**Comment by chentsulin** [comment]
You may want to use `context.session.id` but it will change if session expired.

**Comment by tw0517tw** [comment]
But `context.session.id` is only sender id, you still need to concat it with recipient id / page id.

**Comment by pavei** [comment]
ah ok.. so i will concat the ids! Thanks for help!

**Comment by chentsulin** [comment]
`context.session.id` includes a psid (Page-Scoped ID) so it can be used to identify the user and the page.

> Note: in `message_echos` event, `sender.id` is page id.
