### ISSUE TITLE
Track send messages

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#161]
Hi,

I saw the exemples with (botanalytics, dashbot etc..) but they only track what User Send. I want to track what bot send to user. How can i do this?

Thanks

**Comment by chentsulin** [comment]
All of those libraries should track both of them for you, if not, you can report it as bug.

- [bottender-dashbot](https://github.com/bottenderjs/bottender-dashbot)
- [bottender-botanalytics](https://github.com/bottenderjs/bottender-botanalytics)
- [bottender-botimize](https://github.com/bottenderjs/bottender-botimize)
- [bottender-chatbase](https://github.com/bottenderjs/bottender-chatbase)

We use axios interceptor under the hood to catch outgoing messages:

https://github.com/bottenderjs/bottender-dashbot/blob/c26ca5cba21c633bb6486be799dd0a263c2979ec/src/setInterceptors.js#L4-L21

**Comment by pavei** [comment]
@chentsulin   axios.interceptors.response.use(response)  is there a way to get page id or get the bot context? 

I want to build an ID with  sender-id and recipent-id

**Comment by pavei** [comment]
Here is what i did:

```javascript

module.exports = function setInterceptors(bot, botimize) {
    const {connector: {client: {accessToken, axios}}} = bot;

    // Add a response interceptor
    axios.interceptors.response.use(response => {
        const {config} = response;

        if (config.data) {


            bot.sessions.read("messenger:" + JSON.parse(config.data).recipient.id).then(context => {


                let obj = {
                    conversationId: context._state.fbPageId + "-"+JSON.parse(config.data).recipient.id,
                    jsonMessage: {text: JSON.parse(config.data).message},
                    type: "send",
                }

                console.log(obj);

            }).catch(error => {
                console.log(error);
            })
        }

        return response;
    });
}

**Comment by chentsulin** [comment]
You may not need conversation id, because Page-Scoped ID already be a unique id between user and page.

**Comment by pavei** [comment]
@chentsulin it was the error about setState #162 .. Thanks
