### ISSUE TITLE
[Bug] - Context.State is not  new if  the same user in other [Messenger]

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#162]
Hi!,

I'm developing a robot that works in multiple pages. But with this  #161 i got that the KEY of SessionStore is the userID. I think it should concat with pageId. The code that reproduces the error. 

Case:

1 - Send message in Page 1
2 - Send message in Page 2

```javascript
bot.onEvent(async context => {

    if (!context.state.fbPageId) {
        context.state.fbPageId = context.event.rawEvent.recipient.id
    }
    console.log("F ID:", context.event.rawEvent.recipient.id);
    console.log("S ID:", context.state.fbPageId);

});
```

Console Log:
```bash
F ID: 476947852676691
S ID: 476947852676691
F ID: 131348777471663
S ID: 476947852676691

**Comment by chentsulin** [comment]
@pavei To my knowledge, ids of the same user (psid) should be different between pages, so we even do not know those ids are from the same user.

Could you print the user ids in different pages and show that id is the same?

**Comment by tw0517tw** [comment]
Hi @pavei ,

To set state, you should use `context.setState({ fbPageId: xxx })` not `context.state.fbPageId = xxx`.

Using `context.state.fbPageId = xxx` will accidentally overwrite `initialState` (#163), thus you will get previous state as new `initialState`.

Change your `context.state.fbPageId = xxx` to `context.setState({ fbPageId: xxx })` could resolve this issue. For more information, you can check out our [with-state example](https://github.com/Yoctol/bottender/tree/master/examples/with-state)

**Comment by tw0517tw** [comment]
There's one thing you should keep in mind: the `id`s here are **Page-scoped ID**s. They are unique between pages.
So 1 Facebook User talk to 2 different Pages will get 2 different Page-scoped ID.

**Comment by pavei** [comment]
@tw0517tw now it works fine! I didn't know that IDS are Page Scoped, so i don't need to concat the ids to get unique ID, it is already unique :) 

```javascript
bot.onEvent(async context => {

    if (!context.state.fbPageId) {
        context.setState({fbPageId: context.event.rawEvent.recipient.id})
    }
    console.log("F ID:", context.event.rawEvent.recipient.id);
    console.log("S ID:", context.state.fbPageId);

});


F ID: 359699344142760
S ID: 359699344142760
F ID: 476947852676691
S ID: 476947852676691
