### ISSUE TITLE
[Question] - WebChat

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#167]
Hi, 

Is there a way to use BotTender with some WebChat like MS-WebChat?

I had to change from Microsoft Botbuilder to Bottender because they don't accept multiple facebook pages in one application and i liked Bottender   tooooo much. But i have to keep my application running in MS-Botbuilder because they support WebChat. 

EDIT:

**MS use the Diretline API and sometimes its too slow!**  The same bot with BotTender is too much faster

**Comment by chentsulin** [comment]
Bottender has a browser entry so it can be bundled by bundlers, such as webpack, browserify..., but it only has [very limited functionality](https://github.com/Yoctol/bottender/blob/95cc12046e34125bc11d73667e847a30a8ac0273/src/browser.js#L3-L20) (Bot, MemorySession...) now. You will need to build a custom connector to connect it with UI interface.

Maybe we can have a pluggable web chat in the future, but need to take a look how others implement it first. For example: 
- https://github.com/Microsoft/BotFramework-WebChat

**Comment by pavei** [comment]
Yep, its a nice idea.. i'm using the BotFramework-Webchat for my application. But i think WebChat is strongly connected with [Directline](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-concepts) and now that Microsoft change BotFramework to Azure Service i think they will not open source the Directline server.

**Comment by amitbend** [comment]
This one seems pretty good
https://github.com/botui/botui

BTW - `BotFramework-Webchat` is an option, you just need to provide him with different connector

**Comment by chentsulin** [comment]
Merge this issue into #339
