### ISSUE TITLE
Store all bot messages

### ISSUE THREAD

**Issue by Niko-La** [Yoctol/bottender#168]
How would I store all the `context.event.message.text` for every request from all users without programming it into each handler?

My storing these it will be a great tool to see which commands are popular and most mis-typed.  Also a great way to see indirectly the new commands people are looking for.

**Comment by chentsulin** [comment]
Bottender has three different approaches to get this done, but we haven't figured out which one is better yet.

1. Use server middleware. You can save JSON-parsed request body here, for example:

Express:

```js
const { createServer } = require('bottender/express');

const bot = require('./bot');

const middleware = (req, res, next) => {
  // do something here to save req.body
  next();
};

const server = createServer(bot, {
  webhookMiddleware: middleware,
});
```

Koa:

```js
const { createServer } = require('bottender/koa');

const bot = require('./bot');

const middleware = (ctx, next) => {
  // do something here to save ctx.request.body
  return next();
};

const server = createServer(bot, {
  webhookMiddleware: middleware,
});
```

2. Put it on the top of your root handler

```js
bot.onEvent(async context => {
  if (context.event.isText) {
    // do something here to save context.event.text
  }
  
  // other....
});
```

3. Use plugin (this a hidden feature we are currently working on)

```js
bot.use(async context => {
  if (context.event.isText) {
    // do something here to save context.event.text
  })
});

bot.onEvent(...);
```

**Comment by Niko-La** [comment]
```
const handler = new TelegramHandler()
.onEvent(async context => {
  if (context.event.isText) {
    console.log("test");
  }

  // other....
})


  .onText(/start/i, async context => {
//  console.log(context.session);
  console.log(context );
....

```

I am building of the telegra-builder demo

But now all my messages are just terminating after there onEvent

**Comment by chentsulin** [comment]
One of solutions:

```js
const builder = new TelegramHandler()
  .onText(/start/i, async context => {

  });

/* You can call .build let builder return a handler function */
const hander = builder.build();

bot.onEvent(async context => {
  if (context.event.isText) {
    console.log("test");
  }

  await hander(context);
});
```

**Comment by Niko-La** [comment]
@chentsulin thanks for a solution.  I am new to nodejs handler was not able to get it working.  I managed to just capture all the events that were not commands and store those.

Maybe logging all msg can be a debugging feature that is added in a future release.

**Comment by chentsulin** [comment]
Providing a logging module is not so difficult but I should not assume where the user want to storage their logs. I am not sure if it's enough to just store them into files or mongodb.

**Comment by chentsulin** [comment]
The approaches have been elaborated in https://github.com/Yoctol/bottender/issues/168#issuecomment-358838078
