### ISSUE TITLE
[Feature] support typescript ?

### ISSUE THREAD

**Issue by sj82516** [Yoctol/bottender#177]
It would be better to support typescript.
Thanks

**Comment by chentsulin** [comment]
We currently do not use TypeScript in any of our projects, but I'd love to accept pull request.

**Comment by xxhomey19** [comment]
Starting with TypeScript 2.1, the compiler will no longer complain if there are no type declarations for a module.
Check **Untyped imports** part in [official post](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html).

**Comment by shekohex** [comment]
is there is a tool to convert flow types to ts definitions ? i think that will help

**Comment by chentsulin** [comment]
We already rewrite all types with TS in develop branch and will release 1.0 in early October, so I'm going to close this issue.
