### ISSUE TITLE
Set state does not work after await statement

### ISSUE THREAD

**Issue by kasongoyo** [Yoctol/bottender#180]
I use redis store as my data storage for session data well when I reset state after `await` statement the state data in redis store are not affected but when I do before `await` statement then it works as expected. I am just wondering if there is any issue with setting session or state after async operation.

### The failure version
```js
async (context) => {
 const ticketNum = await promise;
 context.resetState()
 console.log(context.state) // This print the new state but the nothing happens to the redis store
}
```

### The working version
```js
async (context) => {
 context.resetState()
 console.log(context.state) // This print the new state and the same also to the redis store
 const ticketNum = await promise;
}
```

**Comment by chentsulin** [comment]
Hi @kasongoyo, if you have nested async functions,

```js
const handler = async (context) => {
  const ticketNum = await promise;
  context.resetState()
  console.log(context.state) // This print the new state but the nothing happens to the reddis store
};
```

You must await it too:

```js
async (context) => {
  await handler(context);
}
```

It's because session will be written to storage after request end, so we should wait promise done to make sure that we mutate session before it's written.

**Comment by kasongoyo** [comment]
Hi @chentsulin, Thanks for quick reply and surely I nested handlers and I forgot to await as you have showed. Now it's working.
