### ISSUE TITLE
ConsoleBot sendText format

### ISSUE THREAD

**Issue by kpman** [Yoctol/bottender#181]
The consoleBot always sendText with `Bot > ${text}\nYou >`
I think that we should support multiple sentences at a time.

The usage is just like: 
```
await context.sendText('Validation failed!', 'Please try again.');
```

And the output will be:
```
Bot > Validation failed!
Bot > Please try again.
You >
```

**Comment by chentsulin** [comment]
I'd keep API Interface consistent with other platforms, and show `You >` with a delay.

**Comment by kpman** [comment]
Keeping the API consistent is great.
I will try to make a PR.

@chentsulin Do you have any idea about the implementation?
