### ISSUE TITLE
ConsoleBot: improve documentation

### ISSUE THREAD

**Issue by roccomuso** [Yoctol/bottender#183]
Wouldn't be useful to have on the [methods table](https://bottender.js.org/docs/APIReference-Handler#methods-table) also the `ConsoleBot` ? It's useful for testing purposes. I don't have the `onText` event on it.

**Comment by chentsulin** [comment]
Hi, sorry for the late reply.
There are a lot of improvement for `ConsoleBot` will official land and be documented in v0.15, and we will improve docs at that moment. Thanks for your patience.

**Comment by chentsulin** [comment]
Hi @roccomuso, we have more docs for Console now: 
- https://bottender.js.org/docs/Platforms-Console
- https://bottender.js.org/docs/APIReference-ConsoleContext
- https://bottender.js.org/docs/APIReference-ConsoleEvent

**Comment by roccomuso** [comment]
thanks, great!
keep up the great work.
