### ISSUE TITLE
How to add verifyToken for messenger using `registerRoutes `

### ISSUE THREAD

**Issue by shierro** [Yoctol/bottender#187]
Hi,

I want to create a cross platform app, that will allow me to handle multiple bots in a single code base. so I stumbled upon the example here
https://github.com/Yoctol/bottender/blob/master/examples/cross-platform/index.js

On the config used
https://github.com/Yoctol/bottender/blob/master/examples/cross-platform/bottender.config.js

I added `verifyToken` for messenger config but no luck :( App still generates random verify token at start-up.

Is there a way I can do this without using `createServer`?
https://github.com/Yoctol/bottender/blob/master/examples/messenger-hello-world/index.js 

Thanks in advance!

**Comment by chentsulin** [comment]
Pass `verifyToken` as part of third argument:

```js
registerRoutes(server, bots.messenger, { 
  path: '/messenger', 
  verifyToken: config.messenger.verifyToken,
});
```

**Comment by shierro** [comment]
works good. thanks mate!
