### ISSUE TITLE
Security vulnerability found by NSP on Joi 11.3.4 dependency(Hoek 4.2)

### ISSUE THREAD

**Issue by shierro** [Yoctol/bottender#194]
Hello,

Is it feasible if we bump version of `joi` from `11.3.4` to latest?
[NSP](https://github.com/nodesecurity/nsp) found an issue on hoek 
https://nodesecurity.io/advisories/566

![screen shot 2018-02-19 at 2 29 58 pm](https://user-images.githubusercontent.com/12129589/36364909-f69273aa-1581-11e8-98e8-fb9f9d852efa.png)

**Comment by shierro** [comment]
i bumped `joi` to latest and `npm run testonly` works fine

**Comment by chentsulin** [comment]
It seems that latest joi (13.x) drop support for node < v8.9. Is there any approach to fix this and also keep support for node < 8.9?

**Comment by kpman** [comment]
https://github.com/hapijs/joi/issues/1439#issuecomment-366147886

> There is a new version of hoek 4.x.x and 5.x.x. Those are the two versions references by topo 2.x.x and 3.x.x. Clean your dependencies and reinstall.

**Comment by tw0517tw** [comment]
The vulnerability caused by `joi` can be fixed by re-generating `yarn.lock` of bottender, but there is another vulnerability caused by `@slack/client` can not.

![default](https://user-images.githubusercontent.com/1003146/36707007-6514b6fa-1ba7-11e8-931a-84574a921dab.png)

**Comment by chentsulin** [comment]
https://github.com/slackapi/node-slack-sdk/issues/471

**Comment by chentsulin** [comment]
Should be fixed

**Comment by tw0517tw** [comment]
![default](https://user-images.githubusercontent.com/1003146/37198962-01869074-23bb-11e8-997e-66a2be017496.png)
nsp on master 🎉

**Comment by shierro** [comment]
awesome work guys!
