### ISSUE TITLE
[HELP Needed] - Enable get_started & persistent_menu for Multiple pages

### ISSUE THREAD

**Issue by shierro** [Yoctol/bottender#199]
Hi all,

For messenger, do we have a built in support for persistent_menu & get_started buttons for multiple pages? Or do I have to do the request manually for every page?
I created a SO question for the details

https://stackoverflow.com/questions/48980175/bottender-enabling-persistent-menu-and-get-started-button-on-facebook

Any help would be very much appreciated. Thanks in advance!

**Comment by chentsulin** [comment]
We leave messenger profile control to developer, because we can't assume when developers want to set, update or delete bots' messenger profile.

For example, you can have a script like this:

```js
const { MessengerClient } = require('messaging-apis-messenger'); 

const config = require('./bottender.config');

const client = MessengerClient.connect();

const tokens = [ /* */ ]; // get tokens from somewhere

for (let i = 0; i < tokens.length; i++) {
  const token = tokens[i];
  client.setMessengerProfile(config.messenger.profile, {
    access_token: token, // important! pass token to client api
  });
}
```

Or you can call `setMessengerProfile` when you register your token to your database.

**Comment by shierro** [comment]
thanks mate! yeah saw your reply on SO as well
