### ISSUE TITLE
[Question] - Handover Human

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#202]
Is there a way to Stop sending messages to user when a Human type some message?

**Comment by tw0517tw** [comment]
Hi @pavei 

I assume you are talking about Messenger.
You can use the [Handover Protocol](https://developers.facebook.com/docs/messenger-platform/handover-protocol). When passed thread control to another app like Inbox, the text user types will go into `standby` events for the bot. Your bot can then skip those events.

For more information, you can check out our [`messenger-handover` example](https://github.com/Yoctol/bottender/tree/master/examples/messenger-handover)

**Comment by pavei** [comment]
Yep, Thanks
