### ISSUE TITLE
[Docs] - How to create a custom provider

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#227]
Hi! 

I want to use the bottender infra to create my own provider of messages. I saw the ConsoleBot to take it as example. But it could be better if we had a doc about how to create a new Bot.. Directions about wich class should we extends and implements.. etc:)

**Comment by chentsulin** [comment]
Yeah, I totally agree that we should have a guide about how to create a simple connector.  I will work on this next week.

**Comment by pavei** [comment]
Great!! I'll be waiting!

**Comment by pavei** [comment]
Hey! Do you know when it will be ready? I'm waiting.. and my boss is annoying me hehehe

**Comment by chentsulin** [comment]
We only have a draft document now:
https://github.com/bottenderjs/bottenderjs.github.io/pull/56/files

**Comment by pavei** [comment]
Nice!

**Comment by roonie007** [comment]
I almost done with a custom provider , but i am stuck with something , 
how can I trigger the ```bot.onEvent(handler)``` ?

**Comment by roonie007** [comment]
I solved it , I had to add ```createMiddleware``` in each endpoint and it works very good

here is the default function in ```bottender/lib/express/createMiddleware.js```
```javascript
function createMiddleware(bot) {
  const requestHandler = bot.createRequestHandler();

  const wrapper = fn => (req, res, next) => fn(req, res).catch(err => next(err));
  return wrapper(async (req, res) => {
    if (!req.body) {
      throw new Error('createMiddleware(): Missing body parser. Use `body-parser` or other similar package before this middleware.');
    }
    const response = await requestHandler(req.body);
    if (response) {
      res.set(response.headers || {});
      res.status(response.status || 200);
      res.send(response.body || '');
    } else {
      res.status(200);
      res.send('');
    }
  });
}
```

to adapt it to the Provider that i am using, now it looks like this
```javascript
createMiddleware(sessionId, body) {
  const requestHandler = this.bot.createRequestHandler()(Object.assign(body,{sessionId}));

  const wrapper = fn => (req, res, next) =>
    fn(req, res).catch(err => next(err));
  return wrapper(async (req, res) => {
    if (!req.body) {
      throw new Error(
        'createMiddleware(): Missing body parser. Use `body-parser` or other similar package before this middleware.'
      );
    }
    const response = await requestHandler(req.body);

    if (response) {
      res.set(response.headers || {});
      res.status(response.status || 200);
      res.send(response.body || '');
    } else {
      res.status(200);
      res.send('');
    }
  });
}
````

and in here is an example of an endpoint

```javascript
app.post('/sessions/:session_id/******', (req, res) => {
  this.createMiddleware(req.params.session_id,req.body);
  res.status(200).send({ ok: 'ok' });
});
```

**Comment by chentsulin** [comment]
We now have an official doc page here - [Guides: CustomConnector](https://bottender.js.org/docs/Guides-CustomConnector).

**Comment by pavei** [comment]
Very nice! I did one connector for Wabox and it got very nice! Thanks for this support

**Comment by lgertel** [comment]
Hello @pavei how are you doing?
Do you have an example of this kind of implementation? I'm with some difficulties to create a new one, that will receive information from a websocket.

Thanks
