### ISSUE TITLE
Suggest to change "Flexibly → Flexible"

### ISSUE THREAD

**Issue by qshiwu** [Yoctol/bottender#228]
Updated images are as follows.
![materials__20180409_og_forgithub](https://user-images.githubusercontent.com/662387/38478130-5ceff16c-3be9-11e8-9b2b-d9fc2e0925c0.png)
![materials__20180409-06](https://user-images.githubusercontent.com/662387/38478131-5d19f73c-3be9-11e8-9152-ee19c45874bc.png)
![materials__20180409-07](https://user-images.githubusercontent.com/662387/38478132-5d42f09c-3be9-11e8-9d2c-87b8a9966780.png)

**Comment by kpman** [comment]
- [ ] Bottender website
  - head
  - title
  - content
- [ ] Bottender repo
  - README image

**Comment by xxhomey19** [comment]
All has been done. 👍
