### ISSUE TITLE
fix gyp dependencies issue

### ISSUE THREAD

**Issue by wtflink** [Yoctol/bottender#233]
Some users (mainly Windows users) bump into python dependent issue while installing bottender.

Seems like babel-cli and jest have node-pre-gyp dependencies:

```
babel-cli@^6.26.0:
  optionalDependencies:
    chokidar "^1.6.1"

chokidar@^1.6.1:
  optionalDependencies:
    fsevents "^1.0.0"

fsevents@^1.0.0, fsevents@^1.1.1:
  dependencies:
    node-pre-gyp "^0.6.39"



jest@^22.4.3:
  dependencies:
    jest-cli "^22.4.3"

jest-cli@^22.4.3:
  dependencies:
    jest-runner "^22.4.3"

jest-runner@^22.4.3:
  dependencies:
    jest-haste-map "^22.4.3"

jest-haste-map@^22.4.3:
  dependencies:
     sane "^2.0.0"

sane@^2.0.0:
  optionalDependencies:
    fsevents "^1.1.1"

fsevents@^1.0.0, fsevents@^1.1.1:
  dependencies:
    node-pre-gyp "^0.6.39"
```

Should sort out some workaround here, like:
> Install all the required tools and configurations using Microsoft's windows-build-tools using
> `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

via [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by tw0517tw** [comment]
I think we can provide some troubleshooting guides in our document for this node-gyp issue.
