### ISSUE TITLE
Cross platform issue: replyImage and sendImage

### ISSUE THREAD

**Issue by tigercosmos** [Yoctol/bottender#264]
Considering a condition:
A bot for two platform: a free account Line bot and a Messenger bot.
If I want to reply an image for a message. For Line, I would call `replyImage`(because I use free account), but there's no `replyImage` for Messenger, so I would need to call `sendImage`. But I cannot call `sendImage` directly, because I use free account for Line.

A simple way to solve this, I write a tricky code for this: 
```js
async function platformReplyImage(context, url) {
    if (config.chatroomPlatform == 'messenger') {
        await context.sendImage(url)
    } else {
        await context.replyImage(url);
    }
}
```

I think it can be a feature for later version to solve this kind problem.(so as `sendText`)

**Comment by tw0517tw** [comment]
Hi @tigercosmos ,

For the stable release (`bottender@0.14.34` or `bottender@latest`), we have put platform string into context so you can determine there. Maybe it's a better way than use config to check platform.
```js
if (context.platform === 'messenger') {
  // messenger code
}
```

In the beta version (`bottender@0.15.0-beta.9` or `bottender@next`), we add some new features to LINEBot including setting default send method so you can choose whether to use Reply or Push APIs.
```js
const bot = new LINEBot({
  sendMethod: 'reply', // or 'push'
  shouldBatch: true,
  ...otherConfig
});
```
Then you can call send methods like `sendText()` or `sendImage()` and bottender will automatically use Reply API.

Furthermore, with the `shouldBatch` option sets to `true`, bottender will batch all the messages and send them per 5 messages so you don't have to worry about the one-time reply token. (If using Reply API, bottender will slice the messages to the length of 5 and ignore the rest.)

```js
// or you can use sendText() if you set sendMethod to 'reply'
await context.replyText('aaa');
await context.replyText('bbb');

// will call Reply API only once with array of 2 messages
```

The beta features are not documented yet, but you can see the PRs here:
- https://github.com/Yoctol/bottender/pull/242
- https://github.com/Yoctol/bottender/pull/244

**Comment by tigercosmos** [comment]
I have another question about how to `new` a `bot` if I want to cross platform.
as you say, `context` can know which platform from `context.platform`.
However, before it we need to either `new MessengerBot` or ` new LineBot`.
Currently I just use:
```js
const bot = (process.env.chatbotPlatform == 'messenger') ? new MessengerBot() : new LineBot();
```
I am worried about there is a smarter way.

**Comment by tw0517tw** [comment]
Hi @tigercosmos ,

It's OK to construct different type of Bot with environment variables. In fact, we are currently using something like
```js
const bot =
  process.env.USE_CONSOLE_BOT === 'true'
    ? new ConsoleBot({
        fallbackMethods: true,
      })
    : new MessengerBot({ messengerConfig });
```
when developing our own projects.

**Comment by chentsulin** [comment]
This question has been well-answered, so I am going to close this issue.

By the way, `bottender-compose` also has an util function to help this:
https://github.com/Yoctol/bottender-compose#platform
