### ISSUE TITLE
Bot keeps sending multiple requests?

### ISSUE THREAD

**Issue by JordanVScher** [Yoctol/bottender#267]
Hi. I've been trying to create a simple bot with a menu using this package but I've been running into one problem: My bot keeps sending multiples requests to the Facebook webhook. I've been using ngrok, and when I click on a quick_reply button or use the persistent menu I see multiple requests passing through ngrok. Sometimes this also sends the same message multiple times to my messenger bot. This also makes my app reach the api limit very quickly, halting development. Any ideas?

Here's the code: https://github.com/JordanVScher/posa_chatbot/blob/master/index.js

**Comment by tw0517tw** [comment]
Hi @JordanVScher ,

In the most cases it's because of Messenger's `message_echoes` events. Check #134 maybe it's helpful.

**Comment by JordanVScher** [comment]
Hi. Thanks for your help. I tried those solutions but neither worked. I don't have the messages_echoes webhook selected and trying to filter out !context.event.isEcho also failed. I have tried using a different app and a different page but it didn't work. Currently all selected events I have are the messages and messaging_postbacks and even then it keeps doing that.

**Comment by tw0517tw** [comment]
IIRC, the requests show on ngrok dashboard are incoming requests FROM Facebook, not outgoing ones. So it seems that your bot server was receiving extra events from Facebook. 

Maybe you can log all the events (by `console.log(context.event.rawEvent)`), or log all the incoming requests (by setting `DEBUG` environment variable to `bottender/bot/Bot`) to see what events are sending to your bot server.

**Comment by JordanVScher** [comment]
All I'm loggin is a bunch of the following: 
`{ sender: { id: '1681920771857614' },
  recipient: { id: '1727924760620064' },
  timestamp: 1526401022391,
  delivery: 
   { mids: [ 'mid.$cAAZ5fflaYzNpldyASljZJc3-JSVw' ],
     watermark: 1526401022150,
     seq: 0 } }
`
Debug gives me the same with more parameters: 
` bottender/bot/Bot {
  bottender/bot/Bot   "object": "page",
  bottender/bot/Bot   "entry": [
  bottender/bot/Bot     {
  bottender/bot/Bot       "id": "1727924760620064",
  bottender/bot/Bot       "time": 1526401206105,
  bottender/bot/Bot       "messaging": [
  bottender/bot/Bot         {
  bottender/bot/Bot           "sender": {
  bottender/bot/Bot             "id": "1681920771857614"
  bottender/bot/Bot           },
  bottender/bot/Bot           "recipient": {
  bottender/bot/Bot             "id": "1727924760620064"
  bottender/bot/Bot           },
  bottender/bot/Bot           "timestamp": 1526401206089,
  bottender/bot/Bot           "delivery": {
  bottender/bot/Bot             "mids": [
  bottender/bot/Bot               "mid.$cAAZ5fflaYzNpld9Od1jZJoGEwHvf"
  bottender/bot/Bot             ],
  bottender/bot/Bot             "watermark": 1526401205879,
  bottender/bot/Bot             "seq": 0
  bottender/bot/Bot           }
  bottender/bot/Bot         }
  bottender/bot/Bot       ]
  bottender/bot/Bot     }
  bottender/bot/Bot   ]
  bottender/bot/Bot } +142ms
`
I'm not exactly sure what to make of these. Of course, there's more coming than what I'm expecting. As I said before I've tried using a different app and page.

**Comment by tw0517tw** [comment]
It seems to be the `message_deliveries` events. Unsubscribe those events or filter them using `context.event.isDelivery`.

**Comment by JordanVScher** [comment]
I see. It seems that filtering isDelivery did the trick. Unsubscribing to it doesn't seem to be doing much. I'm still receiving multiple requests but I'm not responding to them. Thank you for your help!
