### ISSUE TITLE
how to setting about redis server?

### ISSUE THREAD

**Issue by CaptainGoos** [Yoctol/bottender#272]
i will use Redis server on AWS, with Beanstalk.
how can setting redis setting about 'host', 'port' ....

Thanks!

**Comment by chentsulin** [comment]
`RedisSessionStore` use [ioredis](https://github.com/luin/ioredis) under the hood, so you can config `host`, `port` using an object:

```
new RedisSessionStore()       // Connect to 127.0.0.1:6379
new RedisSessionStore(6380)   // 127.0.0.1:6380
new RedisSessionStore({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0
})
// Connect to 127.0.0.1:6380, db 4, using password "authpassword"
new RedisSessionStore('redis://:authpassword@127.0.0.1:6380/4')
```

**Comment by CaptainGoos** [comment]
@chentsulin big thanks!!

**Comment by tw0517tw** [comment]
I think we can improve docs in the redis example.
I'll tag this as doc and keep it open.
