### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by wtflink** [Yoctol/bottender#279]
PageInbox here:
https://github.com/Yoctol/bottender/blob/adf8696fb18cfab87fff18b5524626ba011d3ac8/src/context/MessengerContext.js#L272

Inbox here:
https://github.com/Yoctol/bottender/blob/f41fff520195df6ae66e1b7ffe48dd5c739e2eef/src/context/MessengerEvent.js#L707

which one is better, or make it both work

**Comment by tw0517tw** [comment]
I prefer call it by full name PageInbox

**Comment by chentsulin** [comment]
+1 for

`isRequestThreadControlFromInbox` -> `isRequestThreadControlFrom PageInbox`
