### ISSUE TITLE
Proposal: also pass URL query into handler in server adapters

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/bottender#285]
We can merge query and body in `createMiddleware`:

```js
{
  ...query,
  ...body,
}
```

It's useful in custom connectors.

**Comment by tw0517tw** [comment]
For custom connectors, maybe we can give more like request header as #211 mentioned.

**Comment by chentsulin** [comment]
For #211, we may want to pass second argument to requestHandler

express: { req, res }
koa: ctx
micro: { req, res }
restify: { req, res }
