### ISSUE TITLE
Setup on Google Compute Engine

### ISSUE THREAD

**Issue by EvenPeng** [Yoctol/bottender#288]
Hi all,
I'm trying to host a server for LINE bot on GCE instance.
I used "bottender init" to have basic configurations and filled correct token and secret.
Then, I ran "npm start", and the server is working.
However, the line bot is no response at all.
Any suggestions?
Thanks!

**Comment by tw0517tw** [comment]
Hi @EvenPeng ,

Have you tried to verify your webhook URL on LINE developers website? What's the result? 
![default](https://user-images.githubusercontent.com/1003146/41586145-9cc58b26-73de-11e8-8009-0baea60ba5d2.png)

Also, you can set environment variables to see if your server is receiving incoming request.
https://bottender.js.org/docs/Guides-Troubleshooting

**Comment by EvenPeng** [comment]
Hi @tw0517tw 
It shows "An error occurred when sending the webhook."
I also tried the debugger, but it shown nothing on serve side after I click "verify" on the web page.

**Comment by EvenPeng** [comment]
Hi @tw0517tw 
I used "curl https://[MY_URL]".
It shows "curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol"
Is this related to SSL issue?
Thanks!

**Comment by tw0517tw** [comment]
Hi @EvenPeng ,

It seems that the webhook URL you set is wrong. You need to check your server settings.

**Comment by EvenPeng** [comment]
Hi @tw0517tw
Https server is default setting in bottender?
Where should I set path of certification files?
Thanks.

**Comment by tw0517tw** [comment]
`Bottender` supports 4 kinds of Node.js http server, `express`, `koa`, `micro` and `restify`, you can setup the server refer to their own documentation. Also you can use other http server, like `nginx`, as a reverse proxy and setup cert in `nginx`.

The implementaion and deployment detail is up to you.

**Comment by EvenPeng** [comment]
Got it.
I would check configurations of express and GCP.
Thanks a lot!!
