### ISSUE TITLE
FB Messenger doesn't stop sending messages

### ISSUE THREAD

**Issue by jalbarracinv** [Yoctol/bottender#296]
Hello, I just installed and ran messenger script. After setting up webhook and sending the first message. Bottender doesn't stops sending messages (I get loads of them):

Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
....

So I have to stop the script. Any Ideas? Thank you.

**Comment by kpman** [comment]
https://github.com/Yoctol/bottender/issues/134

**Comment by chentsulin** [comment]
We can add warning for sending message when receiving `message_reads`,`message_deliveries`, `message_echoes` events.

**Comment by chentsulin** [comment]
Not we have better warning message and avoid this behavior in `v0.15.0-rc.4`: 

```
calling Send APIs in `message_reads`(event.isRead), `message_deliveries`(event.isDelivery) or `message_echoes`(event.isEcho) events may cause endless self-responding, so they are ignored by default.\nYou may like to turn off subscrtiption of those events or handle them without Send APIs.
```
