### ISSUE TITLE
[question] bottender messenger attachment upload failed 

### ISSUE THREAD

**Issue by CaptainGoos** [Yoctol/bottender#298]
![image](https://user-images.githubusercontent.com/6458969/42356208-66f7c020-80fb-11e8-9044-e7ea99a7e7fc.png)

"✖ TypeError: Cannot read property 'data' of undefined"

Can i attachment upload PDF file to Facebook? or not?

i don't know about that problem.. plz help me..

big thanks !!

**Comment by kpman** [comment]
Hi, @CaptainGoos, thanks for giving feedback.

Could you provide more info about the bottender version & the PDF size?
You can use `$ bottender --version` to get the CLI version.

**Comment by kpman** [comment]
@CaptainGoos Trying to upgrade your bottender version. 
The new version will print more error messages. So I think it will be helpful.
You can install by `npm install bottender@next`.

**Comment by CaptainGoos** [comment]
@kpman big thanks about your reply..
![image](https://user-images.githubusercontent.com/6458969/42430837-eca948a2-836b-11e8-8457-4e693fe24993.png)

i was try about that. but same problem...
anyway big thanks .!!

**Comment by kpman** [comment]
@CaptainGoos 
You install bottender in your local, but it looks like you are executing it from global.
So the error messages looks no different.
If you want to use bottender from global, run `npm install -g bottender@next` and try again.

**Comment by CaptainGoos** [comment]
![image](https://user-images.githubusercontent.com/6458969/42487985-97e3eee0-842d-11e8-96d2-5510c011049d.png)

what is "Error: Request body larger than maxBodyLength limit" ---> maxBodyLength? 

thanks @kpman !!

**Comment by CaptainGoos** [comment]
Big Thanks for quickly support to @tw0517tw  @kpman !!

**Comment by chentsulin** [comment]
Hi @CaptainGoos, this should be fixed in `v0.15.0-rc.4`.
