### ISSUE TITLE
cannot set static verify token for fb messenger

### ISSUE THREAD

**Issue by calledandrey** [Yoctol/bottender#3]
All the time I restart the server new verify token for fb messenger is generated. There is no option to set it static. 

Adding verifyToken property to to bottender.config.json does not help.

**Comment by Calvin-Lin** [comment]
This may help

const server = createServer(bot, {
  verifyToken: '__FILL_YOUR_VERIFY_TOKEN_HERE__'
});

https://bottender.js.org/docs/Guides-Server

**Comment by calledandrey** [comment]
missed it in docs :( Now works, thx!
