### ISSUE TITLE
Example naming

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/bottender#30]
There are so many `with-xxx` examples, hard to determine what type is it. Maybe we could rearrange them with type. For example, 
`with-koa` => `server-koa`
`with-express` => `server-express`
`with memory-session` => `session-memory`
`with-now-deployment` => `deployment-now`.
There could still be some can't be renamed well but it'll be much less `with-xxx`.

**Comment by tw0517tw** [comment]
`with-botimize` => `analysis-botmize`
`with-chatbase` => `analysis-chatbase`

**Comment by chentsulin** [comment]
Nice, just note that don't forget to change link references in the docs.
