### ISSUE TITLE
[question] how to install on ec2 (ubuntu)

### ISSUE THREAD

**Issue by CaptainGoos** [Yoctol/bottender#303]
Hey Guys. thanks a lot about quickly support..

i have a question again :)

yes finally I finished develop my chatbot.
so i want deploy to my real server on AWS (ec2 + ubuntu )
but i had that problem..
![image](https://user-images.githubusercontent.com/6458969/42519580-8a5a9f74-848e-11e8-998c-fdae2bd10940.png)

i can not use cli (bottender init) functions..

thanks you!

**Comment by CaptainGoos** [comment]
permission is ...
![image](https://user-images.githubusercontent.com/6458969/42519832-183e946c-848f-11e8-9e07-70e19deccfd3.png)

**Comment by kpman** [comment]
@CaptainGoos 
There are two way to use bottender CLI.

1. install on global
`$ npm install -g bottender`
after that you can use `$ bottender init` to init your project.

2. use npx (make sure you npm version is greater than `5.2.0`)
`$ npx bottender init`

**Comment by CaptainGoos** [comment]
i cleared that's problem about by '--no-optional'


![image](https://user-images.githubusercontent.com/6458969/42568170-6ccb9ea6-8536-11e8-8e95-d82d688e58ca.png)

**Comment by tw0517tw** [comment]
I guess you solved it, closing this.
