### ISSUE TITLE
New to bot development

### ISSUE THREAD

**Issue by efleurine** [Yoctol/bottender#308]
I am new to bot development. I saw some framework with support for different conversation flow. Do we have this in bottender?

Thanks.

**Comment by tw0517tw** [comment]
Hi @efleurine .

In Bottender there are many ways to control conversation flow. One of them is to save the current step in state, as you can see [in this issue](https://github.com/Yoctol/bottender/issues/109) #109 . You can design whatever you want in the state object to handle conversation flows.

**Comment by efleurine** [comment]
thanks for your answer @tw0517tw
