### ISSUE TITLE
support Slack Request Signing

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/bottender#312]
Slack has a new request validation method "request signing", we should move to this one.

https://medium.com/slack-developer-blog/build-more-secure-apps-with-request-signing-mutual-tls-9e73f19cc9dd
https://api.slack.com/docs/verifying-requests-from-slack

**Comment by chentsulin** [comment]
Here's an overview of the process to validate a signed request from Slack:

- Retrieve the `X-Slack-Request-Timestamp` header on the HTTP request, and the body of the request.
- Concatenate the version number, the timestamp, and the body of the request to form a basestring. Use a colon as the delimiter between the three elements. For example, `v0:123456789:command=/weather&text=94070`. The version number right now is always `v0`.
- With the help of `HMAC SHA256` implemented in your favorite programming, hash the above basestring, using the Slack Signing Secret as the key.
- Compare this computed signature to the `X-Slack-Signature` header on the request.

**Comment by chentsulin** [comment]
```js
const signingSecret = '....';
const baseString = `v0:${request.headers['X-Slack-Request-Timestamp']}:${request.body}`;

const signature = crypto
  .createHmac('sha256', signingSecret)
  .update(baseString, 'utf8')
  .digest('hex');

return request.headers['X-Slack-Signature'] === signature;
```

**Comment by tw0517tw** [comment]
I consider about the API parameter design of `verifySignature()` for `SlackConnector`. In LINE and Messenger we have
```js
verifySignature(rawBody: string, signature: string)
```
but in Slack we need 2 items from reqeust header. The questions is if we pass whole header to `verifySignature()` like `verifySignature(rawBody, headers)` for Slack, are we going to unify this to LINE and Messenger?

**Comment by tw0517tw** [comment]
Or a more specific version for Slack?

```js
verifySignature(rawBody: string, signature: string, reqeustTimestamp: string)
```

**Comment by chentsulin** [comment]
https://github.com/Yoctol/bottender/releases/tag/v1.3.0
