### ISSUE TITLE
Loop through sessions

### ISSUE THREAD

**Issue by jooray** [Yoctol/bottender#316]
If I understand correctly how the session implementation works, I cannot just loop through all the sessions that were created and send them a message (for example based on session state). I need to react to an event.

Is there a way to create a session object from let's say a mongo collection and then loop through sessions and send the users messages?

Or should I store some part of session away?

My goal is to have a bot that sends one message per week, so I cannot purely react on messages, I need to loop through sessions (and survive bot process restarts). What would be the best approach to do this?

(My suggestion is to have an utility function to do looping through sessions)

**Comment by tw0517tw** [comment]
You can use MongoDB, Redis, or file as your session store and implement a script to access the store and send users messages using [`messaging-apis`](https://github.com/Yoctol/messaging-apis)(the underlying api client used by Bottender).

Examples:
https://github.com/Yoctol/bottender/tree/master/examples/session-file
https://github.com/Yoctol/bottender/tree/master/examples/session-mongo
https://github.com/Yoctol/bottender/tree/master/examples/session-redis

**Comment by chentsulin** [comment]
We can implement `.all` method on SessionStore:

```js
const allSession = await sessionStore.all();
```

Expressjs implemented this feature as well: https://github.com/expressjs/session#storeallcallback

**Comment by jooray** [comment]
Yes please, this would really help

**Comment by chentsulin** [comment]
Hi @jooray, `.all` already be implemented in `v0.15.8`.

https://github.com/Yoctol/bottender/releases/tag/v0.15.8
