### ISSUE TITLE
After session warning ?

### ISSUE THREAD

**Issue by efleurine** [Yoctol/bottender#320]
Warning: Calling `context.setState` after session has been written. Some changes to state will not be saved.
Did you forget to await any async function?

I cannot understand this warning. I tried to look the code source but still not understand why I am getting this.

**Comment by tw0517tw** [comment]
All `context` methods for calling platform APIs are `async` functions, so you need to `await` them in your handlers.

For example if you do
```js
async context => {
  context.sendText('hello');
  context.setState({ foo: 'bar' });
}
```
you'll get the warning.
You should `await` the `sendText` function call.
```js
async context => {
  await context.sendText('hello');
  context.setState({ foo: 'bar' });
}
```

**Comment by chentsulin** [comment]
I hope you solved your problem. If you have further question, you can post it on [stackoverflow and use bottender tag](https://stackoverflow.com/questions/tagged/bottender).
