### ISSUE TITLE
how can i use 'broadcast_messages' ?

### ISSUE THREAD

**Issue by CaptainGoos** [Yoctol/bottender#323]
i want send message to many users by 'broadcast_messages' on facebook messenger? 
(https://developers.facebook.com/docs/messenger-platform/send-messages/broadcast-messages)
but i saw only make label , delete label, get label functions..

not yet support this function?

anyway always big thanks !!

**Comment by tw0517tw** [comment]
Hi @CaptainGoos ,

For sending broadcast messages, you can directly use the underlying messaging client by accessing `bot.connector.client` which will give you the created `messaging-api-messenger` client instance.

[Docs for `messaging-api-messenger` broadcast can be found here.](https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-messenger#broadcast-api)

**Comment by CaptainGoos** [comment]
HI ~ @tw0517tw ^^;
wow big thanks !!

**Comment by tw0517tw** [comment]
Hi @CaptainGoos ,

It's already in `bottender`'s dependencies, so if you do `bot.connector.client` you don't need to explicit run `npm i` for it. But if you would like to use it as a module like `require('messaging-api-messenger')`, it's better to run `npm i` for it to make sure it's list in your `package.json`.
