### ISSUE TITLE
session.user

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#340]
Hello,
I would like to make the user to login to our backend (firebase), once the user logged in, we store the backend userId and status on session.user? If we resetState, will the information of login lost??

Thanks~~

**Comment by chentsulin** [comment]
`resetState` only clean up all of data in `context.state`, but we discourage that mutating `session.user` because we store some important platform user information there and use it to handle response message.

**Comment by yusef-ho** [comment]
I see, thanks

**Comment by yusef-ho** [comment]
@chentsulin 
so what if i store the information of our backend of user in other key in session instead of user in session??

I was trying to assign bot to global then 
```javascript
global.bot.setInitialState({
    firebase: {
        userRecord: userRecord
    }
});
```
but it seems not working.
is there any way we can store user's session information that connecting to our backend??
Thanks

**Comment by tw0517tw** [comment]
Maybe you can try to store users' platform IDs (`session.id` or `session.user.id`) in your backend?

**Comment by chentsulin** [comment]
@yusef-ho

If you want to store some additional information to the current user context, you can try this:

```js
context.setState({
  // key: value 
})
```

See [with-state example](https://github.com/Yoctol/bottender/blob/master/examples/with-state/index.js).

Be careful that the session and the session state could be expired depends on your session store config.

If you want to link this platform user and your backend user information forever and never be expired, you should save platform user id (`context.session.user.id`) to your database user table (or collection).

**Comment by chentsulin** [comment]
Hi @yusef-ho 
In Bottender v1, we deprecated this user profile auto-fetching features. You may fetch profile explicitly using corresponding API, for example, in Messenger:

```js
const user = await context.getUserProfile();
```
