### ISSUE TITLE
[Feature]  Will buttender support line pay ?

### ISSUE THREAD

**Issue by t42ji2ji** [Yoctol/bottender#345]
Hi, I'm really enjoying this project you create.
I just wanna know will you support line pay in bottender?

**Comment by tw0517tw** [comment]
Hi @t42ji2ji ,

I'm not so familiar with LINE Pay, co correct me if I'm wrong.
I think this can be done by opening a webview or LIFF to a website intergrated with LINE Pay. Maybe you can elaborate more about what kind of support do you want in Bottender?

**Comment by chentsulin** [comment]
@t42ji2ji FYI, we start trying to implement those methods in this PR:
https://github.com/Yoctol/messaging-apis/pull/409

**Comment by t42ji2ji** [comment]
@chentsulin  Thanks a lot !!!!!
You guys are amazing

**Comment by chentsulin** [comment]
Bottender has nothing to do here now, but we can use those feature directly from `messaging-api-line`:
https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-line#line-pay
