### ISSUE TITLE
[LINE] support 2018/11/08 change

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/bottender#367]
https://developers.line.me/en/news/#specification-change-for-the-messaging-api-2018-11-08

## New properties are added to webhook events

- The body of webhook events now includes the user ID (destination) of a bot that should receive the webhook events. For more information, see Request body.
- New information is available in message objects for image, video, and audio messages. For more information, see Image, Video, and Audio.

Correction on November 9, 2018 : MID -> user ID

**Comment by chentsulin** [comment]
```json
{
  "destination": "xxxxxxxxxx", 
  "events": [
    {
      "replyToken": "0f3779fba3b349968c5d07db31eab56f",
      "type": "message",
      "timestamp": 1462629479859,
      "source": {
        "type": "user",
        "userId": "U4af4980629..."
      },
      "message": {
        "id": "325708",
        "type": "text",
        "text": "Hello, world"
      }
    },
    {
      "replyToken": "8cf9239d56244f4197887e939187e19e",
      "type": "follow",
      "timestamp": 1462629479859,
      "source": {
        "type": "user",
        "userId": "U4af4980629..."
      }
    }
  ]
}
```

**Comment by chentsulin** [comment]
done.
