### ISSUE TITLE
[Bug][Line] the message was modified and wrong

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#374]
Hello, 
I was using Bottender with Bottender-Compose, the following is my code. and if i send text/image to the bot, it passed in first condition validator no matter what type of message and the type was modified incorrect
<img width="715" alt="screen shot 2018-11-17 at 4 02 46 pm" src="https://user-images.githubusercontent.com/33569998/48658774-640cab00-ea82-11e8-955a-e4a64231ea2f.png">

```javascript
.onMessage(condition([
        // Handle Document
        [async context => {
            const message = context.event.message;
            if (message.type = 'file') return true
        }, require('./onReceivedFileMessage')],

        // Handle Image
        [async context => {
            const message = context.event.message;
            if (message.type = 'image') return true
        }, require('./onReceivedImageMessage')]
    ]))
```

**Comment by chentsulin** [comment]
You should use `==` or `===` to compare between two strings.

Assignment always be considered as `true` in if `condition`:

```js
if (message.type = 'file') {
  // code always be executed...
}
```

Eslint's `no-cond-assign` rule can help a lot to detect this kind of mistake:
https://eslint.org/docs/rules/no-cond-assign

**Comment by tw0517tw** [comment]
As this seems not to be a bug of bottender, I'm going to modify the title and closing this issue.

**Comment by yusef-ho** [comment]
ahahah, sorry for that... how stupid i'm, sorry for my typo
