### ISSUE TITLE
[QUESTION] - Setting up messenger webhook

### ISSUE THREAD

**Issue by iZEY** [Yoctol/bottender#375]
Hello,

I cannot figure out how to set up bottender with facebook messenger.
I tried it with the basic sample together with ngrok. However, the tutorial says that 

> This example shows that you just add an optional object { ngrok: true } to createServer. Then Bottender will start using ngrok to serve your server and log webhook url on terminal automatically. 

but I dont even see a logged webhook url

```
H:\workspace\bottender\example>npm start dev

> example@0.1.0 start H:\workspace\bottender\example
> node index.js "dev"

verify token: Pwhatever3
server is running on 5000 port...
```

index.js:

```JS
const { MessengerBot } = require('bottender');
const { createServer } = require('bottender/express');

const config = require('./bottender.config.js').messenger;

const bot = new MessengerBot({
  accessToken: config.accessToken,
  appSecret: config.appSecret
});

bot.onEvent(async context => {
  await context.sendText('Hello World');
});

const server = createServer(bot, { ngrok: true });

server.listen(5000, () => {
  console.log('server is running on 5000 port...');
});
```

What do I have to do to receive messages from facebook messenger?

**Comment by iZEY** [comment]
Okay, I figured it out (at least a little bit).
I removed `{ ngrok: true }`, just start `ngrok http 5000` and then the bottender bot plus setting the webhook.

**Comment by iZEY** [comment]
How can I let bottender set up the webhook automatically?

**Comment by wtflink** [comment]
I think in normal situation we won't change webhook very often. So this part isn't really optimized, I have to admit.

My solution is run bot, ngrok, bottender messenger set webhook in one script.

But for development, we should be able to provide a better environment. If you have any idea, just throw it out, and let's see how it goes.

**Comment by iZEY** [comment]
Unfortunately I am quite new to JavaScript, node.js and bots in general, but if I come up with an idea I will let you know! Until then I will use a script aswell.

**Comment by chentsulin** [comment]
Hi @iZEY, It seems that the question has been answered.
FYI, We are building Bottender v1.0, and it will be released in early October. In that version, you can start dev server and `ngrok` in one script - `bottender dev`, but still need to do `bottender messenger set webhook` separately.
