### ISSUE TITLE
[Telegram] Can't set webhook!

### ISSUE THREAD

**Issue by lgertel** [Yoctol/bottender#380]
Hello everyone!
I have a cross-platform software using bottender that already works with messenger.
I'm tying to build a simple Telegram example without success.

```
bottender telegram webhook set -w https://758dff00.ngrok.io
⚠ We can not find the webhook callback url you provided.
? Are you using ngrok (get url from ngrok server on http://127.0.0.1:4040)? Yes
```

This action goes to timeout after some time. The ngrok is pointing to the right port and everything else seems to work fine. The same example works with Messenger, and i'm able to set the webhook and the messenger endpoint.

Can someone help me?
Thanks

**Comment by wtflink** [comment]
We might miss config the cli alias, so can you kindly try `bottender telegram webhook set --webhook https://758dff00.ngrok.io` and see if it works.

This is a regression introduced from some refactor with the cli commands, thanks for reporting this.
