### ISSUE TITLE
Session expiration | Change on runtime?

### ISSUE THREAD

**Issue by lgertel** [Yoctol/bottender#382]
Hello everyone!
I want to know if it's possible to change my session expiration time at runtime via some specific method.

I have a backend application where the user can define the session timeout for the chat application, and I wish to have that applied for the next conversation after the update.

Thanks

**Comment by chentsulin** [comment]
This is not a common feature in a session library. For example, express/session do not support dynamic maxAge either:

https://github.com/expressjs/session/blob/master/README.md

You can store the information in your database and check it on your side.

**Comment by lgertel** [comment]
@chentsulin great! Thanks for you reply.
