### ISSUE TITLE
[Messenger] - context.session.user is not getting "locale" anymore

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#395]
Hi,

Facebook added a new policy to messenger bots. Now i have the approve about "locale" but it still not coming in context.session.user

![image](https://user-images.githubusercontent.com/554537/51603667-9824a200-1ef1-11e9-9e07-0210a20927de.png)

```javascript
 { _updatedAt: '2019-01-23T11:17:23.679Z',
  first_name: 'Vinicius',
  last_name: 'Pavei',
 profile_pic: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?psid=2365052303569086&width=1024&ext=1550834243&hash=AeRo45e0kwJgzszv'
}

**Comment by pavei** [comment]
It doesn't work.. i'm thinking that 
``` 
user = await this._client.getUserProfile(..
```
is not returing the locale..

**Comment by chentsulin** [comment]
Ah, I see. Also need this PR to support this:
https://github.com/Yoctol/messaging-apis/pull/431/files

**Comment by chentsulin** [comment]
@pavei You can try bottender v0.15.16 and see if it works.

**Comment by pavei** [comment]
@chentsulin i did the update, but the "fields" default is on MessengerConnector ( https://github.com/Yoctol/messaging-apis/pull/431/files#diff-20628948de9443b49d6d62ec105cb743R353)  ['id', 'name', 'first_name', 'last_name', 'profile_pic'] and on updateSession  still the code below, that is not defined the "fields"

```
 user = await this._client.getUserProfile(senderId, {
            access_token: customAccessToken,
          });

```

**Comment by pavei** [comment]
When i did this code, it works:

```
  try {
          user = await this._client.getUserProfile(senderId, {
            access_token: customAccessToken,
            fields: ['id', 'name', 'first_name', 'last_name', 'profile_pic', 'locale']
          });
        } catch (e) {
          (0, _warning.default)(false, 'getUserProfile() failed, `session.user` will only have `id`');
          console.error(e);
        }

**Comment by chentsulin** [comment]
Hi @pavei, In Bottender v1, we disable the behavior of auto-fetching profile by default.  
And you can get `locale` by adding `fields` options to `context.getUserProfile` api: 
https://github.com/Yoctol/bottender/releases/tag/v1.0.1
