### ISSUE TITLE
[Line] differentiate between image sent from gallery or camera roll

### ISSUE THREAD

**Issue by shanmarkus** [Yoctol/bottender#404]
Is there any function to detect where the image came from ? if not, is it possible to force user only to upload image via camera roll ?

Regards,

**Comment by tw0517tw** [comment]
Hi @shanmarkus ,

It seems LINE doesn't provide this kind of detection in the [Image Messages Event](https://developers.line.biz/en/reference/messaging-api/#wh-image). If you'd like to encourage users to use camera or camera roll, check [Camera Action](https://developers.line.biz/en/reference/messaging-api/#camera-action) and [Camera Roll Action](https://developers.line.biz/en/reference/messaging-api/#camera-roll-action).

Or you can try to [send feedback to LINE team in their community forum](https://www.line-community.me/questions).

**Comment by chentsulin** [comment]
It's impossible to detect the image source, so I am going to close this issue.
