### ISSUE TITLE
next in middleware

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#409]
Hello, 
Can we pass something in next?
or how could i use something retrieved from the step and pass to next step??
Thanks

**Comment by chentsulin** [comment]
You can put some custom key on context, just like what express and koa middleware do.

```js
async context => {
  context.myKey = 'myValue'
};
```

**Comment by yusef-ho** [comment]
@chentsulin ok, thanks.
currently, i'm using 'context.requestContext.res.locals.myKey = 'myValue'
