### ISSUE TITLE
bottender-compose in middlewares

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#410]
Hello, 
Can we use bottender-compose in middlewares as i posted here
https://github.com/Yoctol/bottender/issues/387#issuecomment-469995993
Thanks

**Comment by chentsulin** [comment]
Hi @yusef-ho, 
In Bottender v1, we don't recommend using `middleware` anymore. You may replace them with [`chain`](https://bottender.js.org/docs/the-basics-chain) which works better with `bottender-compose`.
