### ISSUE TITLE
session-file @win10  had reported error

### ISSUE THREAD

**Issue by KentTai** [Yoctol/bottender#413]
I practice a linebot and use bottender to store session @ file but got error as following ,
it looked seem to  filename with ":" symbol , any ideas ? thanks  , 
my os is win 10 

state: ${JSON.stringify(context.state)}
{ [Error: EINVAL: invalid argument, rename 'd:\57_NodeJSCode\10_Line\demo1\sessions\line:U6763403ca9f0219ad0cf9c509a8e354d.json1d2ef1c2-5ef7-48ae-b69d-121e877d3895.tmp' -> 'd:\57_NodeJSCode\10_Line\demo1\sessions\line:U6763403ca9f0219ad0cf9c509a8e354d.json']
  errno: -4071,
  code: 'EINVAL',
  syscall: 'rename',
  path:
   'd:\\57_NodeJSCode\\10_Line\\demo1\\sessions\\line:U6763403ca9f0219ad0cf9c509a8e354d.json1d2ef1c2-5ef7-48ae-b69d-121e877d3895.tmp',
  dest:
   'd:\\57_NodeJSCode\\10_Line\\demo1\\sessions\\line:U6763403ca9f0219ad0cf9c509a8e354d.json' }

**Comment by chentsulin** [comment]
I can confirm that `:` in the filename is not supported by Windows.

What is the better alternative character here to support both Windows and others?
cc @tw0517tw

**Comment by tw0517tw** [comment]
I think `-`, `_` or even something like `__` should work well. As far as I know, the platforms are not using these characters as user id.

**Comment by JordanVScher** [comment]
Any news on this? Or any workaround?
