### ISSUE TITLE
Bot.connector.client.connect is not a fuction

### ISSUE THREAD

**Issue by hardcod3r** [Yoctol/bottender#414]
Hi. First of all thank you for this perfect work.
I have a question
im trying to access bot.connector.client an use all its functions
my file looks like this
```
const { MessengerBot } = require('bottender');
const { createServer } = require('bottender/express');
const bot = new MessengerBot({
  appSecret: config.appSecret,
  mapPageToAccessToken
});
const client = bot.connector.client.connect(mapPageToAccessToken);
```
It gives me this error
`TypeError: bot.connector.client.connect is not a function`

How can do this;
for example how can use setMessengerProfile();
I cant see similar function to use with context..
Thank you in advance

**Comment by chentsulin** [comment]
Hi @hardcod3r, `MessnegerBot` creates `MessengerConnector` and `MessengerClient` automatically, so you don't need to call `.connect()` by yourself. 

Just access it directly using `bot.connector.client`:

```js
const bot = new MessengerBot({
  appSecret: config.appSecret,
  mapPageToAccessToken
});

bot.connector.client.setMessengerProfile(/* ... */)
```

**Comment by hardcod3r** [comment]
Thank you @chentsulin for your response;
I think that bot.connector.client not accept mapPageToAccessToken as accessToken.
I have this snippet to get current access token from db
async function mapPageToAccessToken(pageId) {
   await Pages.query().where('page_id', pageId).first().asCallback(function (err, page) {
    const Token = page.session_token;
    return Token; 
    });
  
}
const bot = new MessengerBot({
  appSecret,
  mapPageToAccessToken,
  appId,
  verifyToken, 
  sessionStore,
  sync,
});
Bot works just fine. But client returns this error 
Error: Messenger API - 2500 OAuthException
Any thoughts?

**Comment by hardcod3r** [comment]
I found something about it..
I tried to assign this in a context async function
`context._client._accessToken = context._customAccessToken;`
It seems works good.. But i do not know if is right
