### ISSUE TITLE
Multiple apps fetched by database

### ISSUE THREAD

**Issue by hardcod3r** [Yoctol/bottender#415]
Hi. Is there any way to setup new MessengerBot with details from database by pageId?
Thank you

**Comment by wtflink** [comment]
Would you mind provide more info, such as what's the actual problem you are trying to solve or why you are doing this in what scenario, it should help us answering this question.

I find it a bit odd dealing with multiple apps and pages at the same time.

**Comment by chentsulin** [comment]
hi @hardcod3r,
You can find the multi-pages example, and see how mapPageToAccessToken works:
https://github.com/Yoctol/bottender/blob/a59e4b4c7f886721d73bb1ae03c43da27e3fc27a/examples/messenger-multi-pages/index.js#L12-L25

And replace `mapPageToAccessToken` by your database query function:

```js
const mapPageToAccessToken = pageId => {
  return fetchAccessTokenFromDatabase(pageId);
};
```
