### ISSUE TITLE
Failed validation. Make sure the validation tokens match.

### ISSUE THREAD

**Issue by rihabkallel** [Yoctol/bottender#419]
I deployed the messenger bot on heroku, but I get this error and "Forbidden" in the page.

**Comment by chentsulin** [comment]
Hi @rihabkallel, this error only shows up when verifyToken is wrong

You need to make sure that you use the same token which you filled in or set by API to set up your bottender bot.

Check `Verify Token` field for your webhook subscription:

<img width="1359" alt="螢幕快照 2019-07-14 下午10 57 28" src="https://user-images.githubusercontent.com/3382565/61185350-e047a480-a68a-11e9-8d0e-a287b724a00f.png">

It must match the config for your bottender bot:

https://github.com/Yoctol/bottender/blob/9b1f577b0be51ada39a0bfad21a88d073f836a02/examples/messenger-hello-world/bottender.config.js#L6

**Comment by chentsulin** [comment]
Because it's not active for a while, I am going to close this.
