### ISSUE TITLE
LifeTime State

### ISSUE THREAD

**Issue by roonie007** [Yoctol/bottender#42]
Hey guys 

I have a suggestion , what about a State that will be destroyed after a fixed given number (not in secondes) , like contexts in DialogFlow(api.ai) , maybe smthng like this 

```javascript
context.setState(Object,lifeTime);

//Will be used like this

// 'nickname' and 'asking' will be destroyed at the end of the next event triggering
context.setState({ nickname: context.event.text, asking: false },1);

// 'nickname' and 'asking' will be destroyed at the end of the third event triggering
context.setState({ nickname: context.event.text, asking: false },3);
```

keep the good work

**Comment by chentsulin** [comment]
Hi @roonie007, are there any examples show that we will need to destroy some state values after fixed number steps?

IMO, we can explicitly `setState` or `resetState` after hearing something or receiving some event. 

For example:

```
- Hi Bottender
```

(one event)

And 

```
- Hi 
- Bottender
```

(two events)

Handling state according to what we heard seems better for conversational model.

**Comment by roonie007** [comment]
@chentsulin , here is an example , when using quick replies to get a user location on messenger , we can't send payload with it , so I had to set few data with setState , which i will remove in the next event call , by suggesting lifeTime option , a developer can gain time and few lines using bottender .

```javascript
context.setState(
{ 
	context : WEATHER,
	query : data.result.resolvedQuery,
	type : "location"
});
context.sendQuickReplies({ text: 'I need your location:' }, [{"content_type": "location"}]);
```
and then when the next event fires

```javascript
if(context.event.location)
{
	var coordinates = context.event.location.coordinates ;
	context.setState(
	{ 
		context : null,
		query : null,
		type : null
	});
}
```

as you can see I can't use ```resetState``` because I have other states which I need in few further events

**Comment by chentsulin** [comment]
It seems reasonable to me to keep state and reset it in this case.

You may receive location messages even when you are not asking:

```js
if (context.event.isLocation) {
  if (context.state.isAskingLocation) {
    const coordinates = context.event.location.coordinates;
    context.setState({
      context : null,
      query : null,
      type : null
    });
  } else {
    // Should we do something else here?
  }
}
```

If some state should be grouped together, we can put them into an object:

```js
context.setState({
  xxx: {
    context : WEATHER,
    query : data.result.resolvedQuery,
    type : 'location',
  },
});
```

Then we can clean them up in one step:

```js
context.setState({
  xxx: null,
});
```

**Comment by roonie007** [comment]
Yep thats almost what i have done :) , but it was just a suggestion that can help some others , less code is always better , anyway thanks :)
