### ISSUE TITLE
Need context from outside of onEvent

### ISSUE THREAD

**Issue by SusValiente** [Yoctol/bottender#422]
Hello, I've been working a few weeks with Bottender, trying to make a bot that manages files with the Dropbox API, my problem is that, in order to authenticate an user with dropbox, the user must log in from a browser, and then the Dropox API gives me a redirect URL to get the code/token of that user.

So, i've made a simple route with Localtunnel + express in my index file, here is my main function:

![image](https://user-images.githubusercontent.com/17430715/60838636-71220a00-a1cb-11e9-947f-37e038e00089.png)

So, as you can see here, once I have the userCode as I need, I have no access to the bot context from the endpoint, thus I am unable to store that information.

I thought that calling that route would maybe trigger some event, and I would be able to do something from that, but it triggers nothing. What I really need is to trigger some kind of event from the request.

Any ideas ? Thanks in advance

**Comment by chentsulin** [comment]
Hi @SusValiente, could you elaborate more details on how do you implement this Dropbox authentication on Telegram? It's not clear to me how users open the browser to do the OAuth authentication. 

In general, you need to pass the unique identifier of the target user to the browser and save it somewhere (HTTP session, ...etc), so then you can get the Telegram userId when the user hit the `/auth` route.

Personally, I'd save those code or token to a persistent database (not session store), because the session will get expired at some time.

**Comment by SusValiente** [comment]
Hi @chentsulin  thanks for the tip. The authentication of the Dropbox is made with an inline_keyboard button that redirects to the browser, once the user has logged in, the Dropbox API makes a call to my `/auth` route.
 I thought that storing the token into the database would be better too, but the storage of that element is not my real issue, sorry I didn't clarify that before.
The point is, I need somehow notify the user that the authentication has been made correctly, and for that purpose I need the context to call to `sendMessage`.
All my problems would be solved if somehow I could get the context from that request.

**Comment by chentsulin** [comment]
The conversation context is a combination of the conversation session and the received event. In this case, it didn't receive an event from Telegram, so there is no conversation context here.

You can directly use the underlying telegram massaging API client to send the message:
https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-telegram#sendmessagechatid-text--options---official-docs

And you can get client from `bot.connector.client`. For example:

```js
bot.connector.client.sendMessage(CHAT_ID, 'hi');
```

**Comment by SusValiente** [comment]
Yes that's exactly what I needed, thanks you were a great help.

**Comment by sytabaresa** [comment]
I think that this is a good answer and should be in documentation (the form to access context outside of onEvent handler) in my case, I make a Telegram and Messenger bot and one triggers messages from the other ;)
