### ISSUE TITLE
[Messenger] Session user and app rate limit issues.

### ISSUE THREAD

**Issue by aellanglet** [Yoctol/bottender#424]
Hello !

I was facing an uncommon issue this last weeks with the new updates of FB Messenger and the [app rate limit](https://developers.facebook.com/docs/graph-api/overview/rate-limiting#application-level-rate-limiting).
As you can see on the doc it says that we got 200 request per user per hour and when we call getUserProfile, each args count as a request (so by default it is [`['id', 'name', 'first_name', 'last_name', 'profile_pic']`](https://github.com/Yoctol/messaging-apis/blob/master/packages/messaging-api-messenger/src/MessengerClient.js#L424) which represent 5 requests.

The problem is at the session.user on the context at the top of the library.
Reading the functions and the code i figured out that at every actions with the bot (so every calls at the context), it is calling [this updateSession function](https://github.com/Yoctol/bottender/blob/master/src/bot/MessengerConnector.js#L243) and by default at [line 269](https://github.com/Yoctol/bottender/blob/master/src/bot/MessengerConnector.js#L269) we can skip the `getUserProfile` call thanks to `_skipProfile` which is a boolean set to false by default.

I suggest to set it to true by default or at least to mention it on the documentation for the other users of bottender messenger library !

For people having this issue and wondering how to fix it, I did it like this :
```js
var bot = new MessengerBot({
  accessToken: process.env.accessTokenGlobal,
  appSecret: process.env.appSecretGlobal,
});

bot._connector._skipProfile = true;
```

Thanks for reading, hope it could help some of us and maybe a update will mention it soon !

**Comment by wtflink** [comment]
Wow, does that `getUserProfile` API count each query field as a request? That's really interesting, never expect that behave.

About the default value for `skipProfile`, I already think setting this to true should be the better default value, but at the mean time, we try to make user to have smooth upgrading experience, most of the time we can not change the default behave too fast, that might break a lot of thing.

Also, it make more sense when you put the `skipProfile` as your bot settings.
```js
var bot = new MessengerBot({
accessToken: process.env.accessTokenGlobal,
appSecret: process.env.appSecretGlobal,
skipProfile: true
});
```

**Comment by chentsulin** [comment]
In Bottender v1, `skipProfile` has been renamed to `skipLegacyProfile` and set to `true` by default.
