### ISSUE TITLE
How to register bot inside a post method on already a runnig server

### ISSUE THREAD

**Issue by ArifNawaz36** [Yoctol/bottender#427]
We are making a chatbot platform which will support multi tenancy using bottender. We have a running server and want to register our bots inside post method. ResgiterRoutes method don't allow us to do so, because it starts its own server. We want to register our bots when we post a request on our server. 

Is there any way to do so? Please help us we are stuck at this point.

what we want to achieve? we want that bottender use our already running server not its own.

```js
server = express()

server.post('/message', async (req, res) =>{
  registerRoutes(server, bot, { path: '/message' })
});
```

**Comment by wtflink** [comment]
Hi @ArifNawaz36, `registerRoutes` is a function makes you easier to register your bot to your express server, not to hook up with the platform.
It should work as the [example](https://github.com/Yoctol/bottender/blob/master/examples/cross-platform/index.js) stated.

If you try to run a bot serving multiple channels you can check out the [example](https://github.com/Yoctol/bottender/blob/master/examples/messenger-batch-multi-pages/index.js) here.

**Comment by ArifNawaz36** [comment]
Thanks @wtflink, but we want to call `registerRoutes` inside post method of an already running server, because that is our requirement. We want to use an already running server and when we receive a post request then our bot has to start working. If it can be done or we are doing it wrong, please give us some guidelines because we have tried our best but couldn't find any solution.

**Comment by chentsulin** [comment]
Hi @ArifNawaz36, you should not register routes inside post method and it should not be a requirement. If you use this approach you will lose all of routes you registered by post after you restart the server.

So I think you may want to check out the [example](https://github.com/Yoctol/bottender/blob/master/examples/messenger-batch-multi-pages/index.js)  which provided by @wtflink .
