### ISSUE TITLE
Problem while registering webhook

### ISSUE THREAD

**Issue by beckmx** [Yoctol/bottender#429]
Hello, I am having some problems for a messenger bot, I set up the bot and looks to be running, but if I go to the facebook configuration and try to register the messenger webhook, the problem looks like there there is no real handshake with the server, if I enter to the URL, it shows me a forbidden response and in the console indicates there was an incoming connection. However in the facebook console both the verify token that I set up in the file and the one provided doesnt work. is the webhook available on /webhook?

**Comment by chentsulin** [comment]
Hi @beckmx, which version of bottender you used? Are there any other details or screenshots to show?
