### ISSUE TITLE
Viber Support

### ISSUE THREAD

**Issue by roonie007** [Yoctol/bottender#51]
When will you add Viber to Bottender , it's currently not available .

**Comment by chentsulin** [comment]
This is on the roadmap but may take a few weeks. We are currently working on some other improvements, so it's not first priority in our team now.

We already implemented Viber client, so all we need is connector and event parser.
https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-viber

**Comment by roonie007** [comment]
Thanks guys
