### ISSUE TITLE
[LINE] cannot sendText or reply/push anything in _error in batch mode

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/bottender#525]
In batch mode, the messages will be pushed into a queue and send in `handlerDidEnd` lifecycle. If you got an error from calling LINE API, the reply token can't use twice and  `handlerDidEnd` is over.

**Comment by wtflink** [comment]
![b95c4b39d60c4169d5334e68a4454b31](https://user-images.githubusercontent.com/7692993/68759694-29b0fc00-064b-11ea-9e62-fc0e30b27c43.jpeg)
