### ISSUE TITLE
Browser-only cannot read the message i send to the bot

### ISSUE THREAD

**Issue by Davicii-ii** [Yoctol/bottender#588]
**Describe the bug**

**To Reproduce**
1. Go to 'Browser-only' in examples
2. Call on 'context.event.text'
3. See error '`message: [Exception: TypeError: Cannot read property 'message' of undefined at BrowserEvent'

`**Expected behavior**
Get the bot to respond according to the question I send by reading the message. In 'Browser-only'

**Comment by chentsulin** [comment]
Hi @Davicii-ii, thank you for reporting this bug. I fixed it in #591, please check it out.
