### ISSUE TITLE
cross-platform example

### ISSUE THREAD

**Issue by tigercosmos** [Yoctol/bottender#592]
I remember there were cross-platform examples before, but I don't find them now.
Probably due to the new v1? Will you add examples later?

**Comment by chentsulin** [comment]
It has been renamed to `multiple-channels`:
https://github.com/Yoctol/bottender/tree/master/examples/multiple-channels

And you may want to check this out:
https://bottender.js.org/docs/multi-messaging-channel-support

**Comment by tigercosmos** [comment]
thanks
