### ISSUE TITLE
How can I create HTTPS server by `initializeServer`

### ISSUE THREAD

**Issue by tigercosmos** [Yoctol/bottender#593]
As bottender provides `initializeServer` to create a HTTP server, I am wondering how to use it to create an HTTPS server.

```
const { initializeServer } = require('bottender');
```

I can find tutorials about using raw `express` with `https`.
Since bottender has its own express, I think the thing would be more complex?

**Comment by chentsulin** [comment]
Hi @tigercosmos

In v1 official release, we introduce a new way to integrate with custom server, for example:

```js
const bodyParser = require('body-parser');
const express = require('express');
const { bottender } = require('bottender');

const app = bottender({
  dev: process.env.NODE_ENV !== 'production',
});

const port = Number(process.env.PORT) || 5000;

const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = express();

  server.use(
    bodyParser.json({
      verify: (req, _, buf) => {
        req.rawBody = buf.toString();
      },
    })
  );

  server.get('/api', (req, res) => {
    res.json({ ok: true });
  });

  server.all('*', (req, res) => {
    return handle(req, res);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

You checkout those `custom-server-*` examples:

https://github.com/Yoctol/bottender/tree/master/examples/custom-server-express
https://github.com/Yoctol/bottender/tree/master/examples/custom-server-koa
https://github.com/Yoctol/bottender/tree/master/examples/custom-server-restify
