### ISSUE TITLE
Broken links in the documentation on session

### ISSUE THREAD

**Issue by candy02058912** [Yoctol/bottender#637]
Hi,

I was reading the documentation on sessions: https://bottender.js.org/docs/the-basics-session
I found the links for `the implement detail here` are all broken due to the files no longer exist.

It doesn't affect the documentation itself, so just bringing it up in case if anyone else is wondering about it. 😄

**Comment by chentsulin** [comment]
@candy02058912, We fixed it by rewriting part of the session docs. Thanks for the issue report.
