### ISSUE TITLE
TypeError: nextDialog is not a function

### ISSUE THREAD

**Issue by gordonfang199649** [Yoctol/bottender#653]
**Describe the bug**
When I tested my chatBot, the error as the title says showed up on the terminal. Is there anything I did wrong? I would be thankful to you  if you could provide me with the solution to deal the problem.

`TypeError: nextDialog is not a function
    at n/ode_modules/bottender/dist/bot/Bot.js:37:32
    at Generator.next (<anonymous>)
    at /node_modules/bottender/dist/bot/Bot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/bottender/dist/bot/Bot.js:4:12)
    at Run (/node_modules/bottender/dist/bot/Bot.js:34:16)
    at /node_modules/bottender/dist/bot/Bot.js:158:41
`

**Comment by chentsulin** [comment]
Hi @gordonfang199649,
One of the possible cause is that your entry function may not export correctly. Could you look into your `index.js` and `src/index.js` (if you're using create-bottender-app) and see if your function is exported by `module.exports =`?

**Comment by chentsulin** [comment]
@gordonfang199649 Is there any demo repo to show the problem?

**Comment by gordonfang199649** [comment]
Here's the repository
https://github.com/gordonfang199649/bottenderExample

**Comment by chentsulin** [comment]
Hi @gordonfang199649, I sent a PR to fix the problem in that repo.
https://github.com/gordonfang199649/bottenderExample/pull/1

We still have to improve this error message to something like `you must export your entry action in your index.js file`.

**Comment by gordonfang199649** [comment]
@chentsulin I appreciate your technical assistance. I'll replace linehandler with router as your advice says. thx for helping me.
