### ISSUE TITLE
in TypeScript, parseMode option in context.sendMessage should accepts string 

### ISSUE THREAD

**Issue by hilezi** [Yoctol/bottender#660]
**Describe the bug**

```
TS2345: Argument of type '{ parseMode: "markdown"; }' is not assignable to parameter of type 'SendMessageOption'.
  Types of property 'parseMode' are incompatible.
    Type '"markdown"' is not assignable to type 'ParseMode | undefined'.
```

I get ts(2345) when I create telegram message `context.sendMessage(text, { parseMode })`

The reason I think, the type prop `parseMode?` is restricted in `enum ParseMode`, so it can NOT accept the string.

**To Reproduce**
```ts
// in TypeScript
context.sendMessage(props.text, {
  parseMode: 'markdown', // work-around: as any
})
```

**Expected behavior**
- it accepts string
- OR let me import `enum ParseMode` in somewhere, maybe `import { ParseMode } from 'bottender/dist/types'`

**Screenshots**
null

**Additional context**
- bottender v1.2.0
- typescript v3.7.5
- node v12.14.1

**Comment by etrex** [comment]
hello, please try this following code:

```ts
import { TelegramContext } from "bottender";
import { TelegramTypes as Type } from "messaging-api-telegram";

export default async function App(context: TelegramContext): Promise<void> {
  const parseMode = Type.ParseMode.Markdown;
  await context.sendText("Welcome to Bottender", {
    parseMode
  });
}

```

**Comment by chentsulin** [comment]
@hilezi Currently, we didn't export TS types from `bottender` package directly, but we will export them in v1.3.

**Comment by chentsulin** [comment]
In Bottender 1.3+, import from Bottender directly:

```js
import { TelegramContext, TelegramTypes } from 'bottender';

export default async function App(context: TelegramContext): Promise<void> {
  await context.sendText('Welcome to Bottender', {
    parseMode: TelegramTypes.ParseMode.Markdown,
  });
}
```
