### ISSUE TITLE
Define an array stored regular expressions

### ISSUE THREAD

**Issue by gordonfang199649** [Yoctol/bottender#663]
I'm just wondering if there's any possibility that I can create an array stored kinds of regular expressions and put it in the first parameter of `text`. And then one string can possibly match either one regular expression which I previously defined.

```javascript
async function App(context) {
  return router([
    // // return SayHi when receiving hi or hello or hey text message
    text(['hi', 'hello', 'hey'], SayHi),
  ]);
}
```

**Comment by chentsulin** [comment]
Now it accepts only a string, an array of strings and a regular expression, for example: 

```js
router([
  text('hi', SayHi),
  text(['hello', 'hey'], SayHi),
  text(/hi/, SayHi),
])
```

We may reconsider that if we wanna let it accept an array of regular expressions in the future. However, you can still use one of following ways that I show you below to handle this case:

1. Merging them into one regular expression:

```js
router([
   text(/h(i|ello|ey)/i, SayHi),
]);
```

2. Using multiple `text`:

```js
router([
   text(/hi/i, SayHi),
   text(/hello/i, SayHi),
   text(/hey/i, SayHi),
]);
```

**Comment by gordonfang199649** [comment]
Ok, now I see. Thanks for your answer.
