### ISSUE TITLE
Loading configuration dynamically

### ISSUE THREAD

**Issue by alainheres** [Yoctol/bottender#674]
Is it possible to load the configuration data programmatically as well?
It is often useful to load them from an external resource at the startup.
Thanks

**Comment by chentsulin** [comment]
Hi @alainheres,
Could you elaborate more on the details of what is an "external resource"  and why you need to load config form there?

**Comment by alainheres** [comment]
Let's consider the scenario in which you have to deploy the same basecode on different and separate environments. We are in the situation a third party give us those configuration data only calling an API at run time. 
A possibility would be not to launch the main process with bottender directly but wrap it up preceding it with a call that compose the configuration file ready to be loaded from bottender right after.
So, we are wondering if there is a better way to do it, currently we are doing it programmatically but in the 0.15 version.
I hope I was clear enough.

**Comment by chentsulin** [comment]
I would run a script to prepare the environment variables by calling the API and then execute bottender accordingly. It make a lot of sense and avoid the tricky part of asynchronous configuration.
What do you think?

**Comment by alainheres** [comment]
Yes we can do in this way, thank you anyway!
