### ISSUE TITLE
WhatsApp env vars documentation format

### ISSUE THREAD

**Issue by jmrf** [Yoctol/bottender#710]
In the [whatsApp setup documentation](https://bottender.js.org/docs/en/channel-whatsapp-setup) the docs specify the 3 variables to be exported but doesn't mention the correct format.

`WHATSAPP_ACCOUNT_SID` and `WHATSAPP_AUTH_TOKEN` are straight forward, just need to be copied from Twilio dashboard.

But `WHATSAPP_PHONE_NUMBER` requires the following format `whatsapp:{phone-number-in-e164-format}`. (Not just the phone number but also need the `whatsapp:` part)

This last point didn't seem apparent from the documentation. Thought might help other to mention this.

Happy to contribute to the documentation if that helps.

**Comment by chentsulin** [comment]
Sure, we should definitely mention this. 
@jmrf If you could help contribute this documentation, you could edit this file and sent a PR:
https://github.com/Yoctol/bottender/blob/master/docs/channel-whatsapp-setup.md

You may want to use a block starting with`> **Note:** ....` to highlight it.

Thanks!

**Comment by jmrf** [comment]
> Sure, we should definitely mention this.
> @jmrf If you could help contribute this documentation, you could edit this file and sent a PR:
> https://github.com/Yoctol/bottender/blob/master/docs/channel-whatsapp-setup.md
> 
> You may want to use a block starting with`> **Note:** ....` to highlight it.
> 
> Thanks!

Sorry I missed your reply. Sure, I'll add and submit a PR.

**Comment by chentsulin** [comment]
Thanks! The note is online now.
