### ISSUE TITLE
Can't configure Whatsapp

### ISSUE THREAD

**Issue by pTutu** [Yoctol/bottender#728]
Hi. I've been trying to configure Whatsapp with Twilio sandbox on an existing bot but it's not working. I'm using v1.3.5.

Here's what I did: added the Whatsapp config to channels, set enable to true, left the default path and added the keys and phone number using envs with the same names as the ones on the documentation. 

So I started my node with npm dev run and ngrok on the same port. (I noticed the documentation said to use `npx bottender dev` but that also didn't work and it actually gave me less information than the other way.). Then I configured the URLs on Twilio and tried sending a whatsapp message and all that happens is ngrok says `POST /webhooks/whatsapp  400 Bad Request` and Twilio gives me ` 11200 - HTTP retrieval failure` for every message I send. 

The thing is I can access `/webhooks/whatsapp` just fine, for example, if I open the address on the browser I get an `Internal Server Error` and an error message on the node console. This makes me think that there is something wrong with the way the Twilio keys and phone are configured. I configured the number in this way: `WHATSAPP_PHONE_NUMBER="whatsapp:+xxxxxxxxxxx"`, like mentioned on the previous issue.

I'm using the same Twilio number I used to send the `join xxx-xxx` token, I hope that's the correct number. I tested with another number Twilio gave me but that didn't work either. I tried exchanging the Twilio live keys with the test keys but that also didn't work. 

Would really appreciate some guidance here. Or maybe some error messages telling us what's wrong.

**Comment by chentsulin** [comment]
Hi @pTutu, could you open `http://localhost:4040/` (your ngrok dashboard) in your browser and show me some requests and responses that cause `400 Bad Request` and `11200 - HTTP retrieval failure`?

I was wondering is there any thing could cause the response timeout. 

https://www.twilio.com/docs/api/errors/11200

Could you also try this example with same `.env` settings to help me figure out the problem?
https://github.com/Yoctol/bottender/tree/master/examples/whatsapp-hello-world

**Comment by pTutu** [comment]
Hello, thanks for your attention.
The ngrok dashboard is showing me this: 
```
{
    "error": {
        "message": "WhatsApp Signature Validation Failed!",
        "request": {
            "headers": {
                "x-twilio-signature": "<SOME_TOKEN_HERE>"
            }
        }
    }
}
```

The same thing happened when I used the example project provided. I double checked my Twilio Account SID and Auth Token and I'm sure they are correct. I don't think it's a timeout issue because the Twilio documentation says it waits for a maximum of 15 seconds but here the response takes only a few milliseconds.

**Comment by chentsulin** [comment]
Hi @pTutu,
It's still hard to know what's going on here, but I find that TEST Credentials do not work even in the sandbox and will get this HTTP status 400 error - signature validation failed. If you're using TEST Credentials (on the right side in my picture), you must use LIVE Credentials instead.

<img width="1418" alt="2020-04-15 9 24 17" src="https://user-images.githubusercontent.com/3382565/79342384-a4b27180-7f5f-11ea-9610-e3b4bf7a3d1c.png">

Besides, please make sure your Account SID and Auth Token match the following format:
**ACCOUNT_SID**: length should be 34 and starts with `ACf`.
**AUTH_TOKEN**: length should be 32.

**Comment by pTutu** [comment]
Yeah, I'm using the live credentials but that wasn't the problem. 
I managed to configure twilio on an older project, without using Bottender and it worked correctly, so I know my credentials are correct. And looking at this older project I found a solution to the problem.

It seems that we have to add `server.use(bodyParser.urlencoded({ extended: false }));` after setting the server with `express()`. 
I don't know why this middleware configuration fixes the issue but I have seem it being mentioned on the Twilio docs. For example: https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-express-app-by-validating-incoming-twilio-requests

Maybe this information could be added to the Bottender docs as well? 
Anyway, my problem is fixed. Thanks for your help. :)

**Comment by florianmaxim** [comment]
@chentsulin Alright, I figured it out. I had to remove the the url from the **STATUS CALLBACK URL** in Twilio (other than stated in the docs). The problem doesn't occur anymore now...

**Comment by florianmaxim** [comment]
@chentsulin Sorry, still having troubles to get whatsapp to work with twilio :/

I am using bottender 1.4.6.
I am using LIVE credentials and and added 
`server.use(bodyParser.json({ verify }));
 server.use(bodyParser.urlencoded({ extended: false, verify }));`

if I run it locally in dev mode and tunnel it via ngrok to twilio it actually works fine.
Even though I get an Internal Server Error if I open localhost:3000/webhooks/whatsapp (!)

The error I get is:

`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, o    at Function.from (buffer.js:195:11)
    at WhatsappConnector.verifySignature (C:\Users\florianmaxim\hn-bot\node_modules\bottender\dist\whatsapp\WhatsappConnector.js:76:50)
    at WhatsappConnector.preprocess (C:\Users\florianmaxim\hn-bot\node_modules\bottender\dist\whatsapp\WhatsappConnector.js:84:18)
)
    at Generator.next (<anonymous>)
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\florianmaxim\hn-bot\node_modules\bottender\dist\server\Server.js:4:12)
    at DevServer.run (C:\Users\florianmaxim\hn-bot\node_modules\bottender\dist\server\Server.js:101:16)       
    at DevServer.handleRequest (C:\Users\florianmaxim\hn-bot\node_modules\bottender\dist\server\Server.js:40:21)`
