### ISSUE TITLE
Deploy custom-server-express cannot trigger webhook

### ISSUE THREAD

**Issue by yanaice** [Yoctol/bottender#739]
Refer to [custom-server-express](https://bottender.js.org/docs/en/advanced-guides-custom-server#migrating-an-existing-project-to-custom-express-server)

running `nodemon server.js`
then POST sth to localhost:5000/wekhooks/line and receive Promise which pending forever, i thought it would call to main logic in src/index.js

```
// route for webhook request
  server.all('*', (req, res) => {
    console.log('Hi') <---- i got only this message
    return handle(req, res); <---- ...<Promise> ........pending...
  });
```
Do i misunderstand something?

**Comment by chentsulin** [comment]
Hi @yanaice, could you show me the HTTP request body to help me figure out what's happening?

**Comment by chentsulin** [comment]
I'm afraid that we can't help if we don't have more information or a reproduce minimum example. @yanaice Have you figured out or solved the problem?

**Comment by chentsulin** [comment]
The issue has been inactive for 20 days, so I'm going to close it. If the problem still exists, feel free to reopen it.
