### ISSUE TITLE
How to send messages from bot to user automatically?

### ISSUE THREAD

**Issue by DakshMiglani** [Yoctol/bottender#767]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a bot that periodically sends a message to a user. currently bottender feels like a request / response system. User makes a request, bottender sends a response. Instead, what if bottender reached out to the user automatically?

**Describe the solution you'd like**
A way to send messages to the user directly.

**Describe alternatives you've considered**
I couldn't really find a good alternative, rasa doesn't fit my use case, nor does botpress. I really need it and if there's a way to do it in bottender, I'd love to know what it is.

**Comment by chentsulin** [comment]
Hi @DakshMiglani, 
You can use the `getClient` function to get the underlying API client, for example, in Messenger:

```js
const { getClient } = require('bottender');

const client = getClient('messenger');
```

Then, call API to send the message proactively as follows:

```js
client.sendText('PSID', 'Hello World!');
```

Reference:

- Messenger - https://bottender.js.org/docs/en/api-messenger-client#usage
- Telegram - https://bottender.js.org/docs/en/api-telegram-client#usage
- LINE - https://bottender.js.org/docs/en/api-line-client#usage
- Slack - https://bottender.js.org/docs/en/api-slack-client#usage
- Viber - https://bottender.js.org/docs/en/api-viber-client#usage

**Comment by DakshMiglani** [comment]
@chentsulin Do you guys have a slack or any other communication channel? I've a few questions about bottender before I jump using it into production.

**Comment by chentsulin** [comment]
Sure, we have a Discord: https://discord.com/invite/apNsWBz
You could post your questions there.

**Comment by xshion13** [comment]
i am trying to do the same but using line, then i want to "push" a message to a group, after a sucess it says "you've reached to monthly limit" and statistics says over 400msg sent, but i sent only 1 message, push does a request to my website, if value is true it not push, if value changes to false it sends a push, any way about how to prevent monthly limit?
