### ISSUE TITLE
Direct messages on Slack

### ISSUE THREAD

**Issue by CentaurWarchief** [Yoctol/bottender#8]
Heyo! Very very nice work! Thanks for open-sourcing it! ❤️ 

I wanted to ask to know whether it's a bug or maybe not a not-implemented-yet feature. Currently, when I talk to my bot (sounds crazy huh?) privately I get: 

```
Unhandled promise rejection (rejection id: 21): Error: Slack API - channel_not_found
```

I think I've granted everything I should on Slack. Any guidance?

**Comment by tw0517tw** [comment]
Hi @CentaurWarchief , I'm glad you like Bottender!

Sorry that we haven't try it with Slack DMs. The error is from using wrong API to get group/DM info within the implementation and we'll fix it soon. For now you can only talk with you bot in a public channel.

**Comment by CentaurWarchief** [comment]
@tw0517tw you rock, thanks!
