### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by liangzongshi** [Yoctol/bottender#820]
Warning: `TelegramClient.connect(...)` is deprecated. Use `new TelegramClient(...)` instead.
Warning: `TelegramClient.connect(...)` is deprecated. Use `new TelegramClient(...)` instead.

**Comment by chentsulin** [comment]
Hi @liangzongshi, are you using which version of the `bottender` package?

**Comment by chentsulin** [comment]
Sorry my bad. This warning was introduced by the dependencies upgrade recently.
You could try v1.4.8 to solve it.

**Comment by chentsulin** [comment]
The issue has been solved, so I'm going to close this.
