### ISSUE TITLE
updateSession may take too long in SlackConnector

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/bottender#95]
It may take over 3 seconds so Slack will retry and bot will receive 2 repeat events.

Not sure if we should try speeding up `SlackConnector.updateSession()` or change `Bot.handleRequest()` behavior to respond earlier.

**Comment by tw0517tw** [comment]
After #105 merged, the time it takes should be improved. Closing.

**Comment by tw0517tw** [comment]
It seems to still take more than 3 sec. sometimes and Slack will retry.

**Comment by chentsulin** [comment]
In v1, updating those information in `updateSession` is deprecated and disabled by default, so I'm going to close this.
