### ISSUE TITLE
No documentation for Deployment

### ISSUE THREAD

**Issue by raiiiz** [Yoctol/bottender#955]
**Describe the bug**

**To Reproduce**
2. Call on '....'
3. See error

**No documentation for Deployment**
**Screenshots**

![image](https://user-images.githubusercontent.com/39197883/142960868-1a3344e6-a521-47a9-8bfb-c3bc8f9be35d.png)

**Comment by tw0517tw** [comment]
Hi @raiiiz ,

The i18n part of our docs website is under maintenance now. Sorry for the inconvenience. Please check deployment docs here https://bottender.js.org/docs/advanced-guides-deployment .
